// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: camp/v1/campaign_ad.proto

package campaignv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// انواع کمپین
type CampaignTypeAd int32

const (
	CampaignTypeAd_CAMPAIGN_TYPE_UNSPECIFIED CampaignTypeAd = 0
	CampaignTypeAd_CAMPAIGN_TYPE_AD          CampaignTypeAd = 1 // تبلیغاتی (Google, Meta)
	CampaignTypeAd_CAMPAIGN_TYPE_MTA         CampaignTypeAd = 2 // ایمیلی (Email Marketing)
)

// Enum value maps for CampaignTypeAd.
var (
	CampaignTypeAd_name = map[int32]string{
		0: "CAMPAIGN_TYPE_UNSPECIFIED",
		1: "CAMPAIGN_TYPE_AD",
		2: "CAMPAIGN_TYPE_MTA",
	}
	CampaignTypeAd_value = map[string]int32{
		"CAMPAIGN_TYPE_UNSPECIFIED": 0,
		"CAMPAIGN_TYPE_AD":          1,
		"CAMPAIGN_TYPE_MTA":         2,
	}
)

func (x CampaignTypeAd) Enum() *CampaignTypeAd {
	p := new(CampaignTypeAd)
	*p = x
	return p
}

func (x CampaignTypeAd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampaignTypeAd) Descriptor() protoreflect.EnumDescriptor {
	return file_camp_v1_campaign_ad_proto_enumTypes[0].Descriptor()
}

func (CampaignTypeAd) Type() protoreflect.EnumType {
	return &file_camp_v1_campaign_ad_proto_enumTypes[0]
}

func (x CampaignTypeAd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampaignTypeAd.Descriptor instead.
func (CampaignTypeAd) EnumDescriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{0}
}

// جزئیات مخصوص کمپین‌های تبلیغاتی
type CampaignDetailsAd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // google, meta
	DailyBudget   float64                `protobuf:"fixed64,2,opt,name=daily_budget,json=dailyBudget,proto3" json:"daily_budget,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Keywords      []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignDetailsAd) Reset() {
	*x = CampaignDetailsAd{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignDetailsAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignDetailsAd) ProtoMessage() {}

func (x *CampaignDetailsAd) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignDetailsAd.ProtoReflect.Descriptor instead.
func (*CampaignDetailsAd) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignDetailsAd) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CampaignDetailsAd) GetDailyBudget() float64 {
	if x != nil {
		return x.DailyBudget
	}
	return 0
}

func (x *CampaignDetailsAd) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CampaignDetailsAd) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// جزئیات مخصوص کمپین‌های ایمیلی
type EmailCampaignDetailsAd struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateId       string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SenderName       string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderEmail      string                 `protobuf:"bytes,4,opt,name=sender_email,json=senderEmail,proto3" json:"sender_email,omitempty"`
	RecipientListIds []string               `protobuf:"bytes,5,rep,name=recipient_list_ids,json=recipientListIds,proto3" json:"recipient_list_ids,omitempty"` // لیست مخاطبین
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmailCampaignDetailsAd) Reset() {
	*x = EmailCampaignDetailsAd{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCampaignDetailsAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCampaignDetailsAd) ProtoMessage() {}

func (x *EmailCampaignDetailsAd) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCampaignDetailsAd.ProtoReflect.Descriptor instead.
func (*EmailCampaignDetailsAd) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{1}
}

func (x *EmailCampaignDetailsAd) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailCampaignDetailsAd) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EmailCampaignDetailsAd) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *EmailCampaignDetailsAd) GetSenderEmail() string {
	if x != nil {
		return x.SenderEmail
	}
	return ""
}

func (x *EmailCampaignDetailsAd) GetRecipientListIds() []string {
	if x != nil {
		return x.RecipientListIds
	}
	return nil
}

type CreateCampaignRequestAd struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScheduledAt    int64                  `protobuf:"varint,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// استفاده از oneof برای انتخاب یکی از انواع جزئیات
	//
	// Types that are valid to be assigned to Details:
	//
	//	*CreateCampaignRequestAd_AdDetails
	//	*CreateCampaignRequestAd_EmailDetails
	Details       isCreateCampaignRequestAd_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequestAd) Reset() {
	*x = CreateCampaignRequestAd{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequestAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequestAd) ProtoMessage() {}

func (x *CreateCampaignRequestAd) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequestAd.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequestAd) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCampaignRequestAd) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateCampaignRequestAd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequestAd) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *CreateCampaignRequestAd) GetDetails() isCreateCampaignRequestAd_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateCampaignRequestAd) GetAdDetails() *CampaignDetailsAd {
	if x != nil {
		if x, ok := x.Details.(*CreateCampaignRequestAd_AdDetails); ok {
			return x.AdDetails
		}
	}
	return nil
}

func (x *CreateCampaignRequestAd) GetEmailDetails() *EmailCampaignDetailsAd {
	if x != nil {
		if x, ok := x.Details.(*CreateCampaignRequestAd_EmailDetails); ok {
			return x.EmailDetails
		}
	}
	return nil
}

type isCreateCampaignRequestAd_Details interface {
	isCreateCampaignRequestAd_Details()
}

type CreateCampaignRequestAd_AdDetails struct {
	AdDetails *CampaignDetailsAd `protobuf:"bytes,4,opt,name=ad_details,json=adDetails,proto3,oneof"`
}

type CreateCampaignRequestAd_EmailDetails struct {
	EmailDetails *EmailCampaignDetailsAd `protobuf:"bytes,5,opt,name=email_details,json=emailDetails,proto3,oneof"`
}

func (*CreateCampaignRequestAd_AdDetails) isCreateCampaignRequestAd_Details() {}

func (*CreateCampaignRequestAd_EmailDetails) isCreateCampaignRequestAd_Details() {}

type CampaignAd struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Type           CampaignTypeAd         `protobuf:"varint,5,opt,name=type,proto3,enum=campaign.v1.CampaignTypeAd" json:"type,omitempty"` // نوع کمپین
	ScheduledAt    int64                  `protobuf:"varint,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// جزئیات بازگردانده شده
	//
	// Types that are valid to be assigned to Details:
	//
	//	*CampaignAd_AdDetails
	//	*CampaignAd_EmailDetails
	Details       isCampaignAd_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignAd) Reset() {
	*x = CampaignAd{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignAd) ProtoMessage() {}

func (x *CampaignAd) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignAd.ProtoReflect.Descriptor instead.
func (*CampaignAd) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{3}
}

func (x *CampaignAd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CampaignAd) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CampaignAd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CampaignAd) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CampaignAd) GetType() CampaignTypeAd {
	if x != nil {
		return x.Type
	}
	return CampaignTypeAd_CAMPAIGN_TYPE_UNSPECIFIED
}

func (x *CampaignAd) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *CampaignAd) GetDetails() isCampaignAd_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CampaignAd) GetAdDetails() *CampaignDetailsAd {
	if x != nil {
		if x, ok := x.Details.(*CampaignAd_AdDetails); ok {
			return x.AdDetails
		}
	}
	return nil
}

func (x *CampaignAd) GetEmailDetails() *EmailCampaignDetailsAd {
	if x != nil {
		if x, ok := x.Details.(*CampaignAd_EmailDetails); ok {
			return x.EmailDetails
		}
	}
	return nil
}

type isCampaignAd_Details interface {
	isCampaignAd_Details()
}

type CampaignAd_AdDetails struct {
	AdDetails *CampaignDetailsAd `protobuf:"bytes,7,opt,name=ad_details,json=adDetails,proto3,oneof"`
}

type CampaignAd_EmailDetails struct {
	EmailDetails *EmailCampaignDetailsAd `protobuf:"bytes,8,opt,name=email_details,json=emailDetails,proto3,oneof"`
}

func (*CampaignAd_AdDetails) isCampaignAd_Details() {}

func (*CampaignAd_EmailDetails) isCampaignAd_Details() {}

type CreateCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCampaignResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCampaignAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignAdRequest) Reset() {
	*x = GetCampaignAdRequest{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignAdRequest) ProtoMessage() {}

func (x *GetCampaignAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignAdRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignAdRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{5}
}

func (x *GetCampaignAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *CampaignAd            `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{6}
}

func (x *GetCampaignResponse) GetCampaign() *CampaignAd {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_ad_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_camp_v1_campaign_ad_proto protoreflect.FileDescriptor

const file_camp_v1_campaign_ad_proto_rawDesc = "" +
	"\n" +
	"\x19camp/v1/campaign_ad.proto\x12\vcampaign.v1\"\x8d\x01\n" +
	"\x11CampaignDetailsAd\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fdaily_budget\x18\x02 \x01(\x01R\vdailyBudget\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\"\xc5\x01\n" +
	"\x16EmailCampaignDetailsAd\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12!\n" +
	"\fsender_email\x18\x04 \x01(\tR\vsenderEmail\x12,\n" +
	"\x12recipient_list_ids\x18\x05 \x03(\tR\x10recipientListIds\"\x91\x02\n" +
	"\x17CreateCampaignRequestAd\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fscheduled_at\x18\x03 \x01(\x03R\vscheduledAt\x12?\n" +
	"\n" +
	"ad_details\x18\x04 \x01(\v2\x1e.campaign.v1.CampaignDetailsAdH\x00R\tadDetails\x12J\n" +
	"\remail_details\x18\x05 \x01(\v2#.campaign.v1.EmailCampaignDetailsAdH\x00R\femailDetailsB\t\n" +
	"\adetails\"\xdd\x02\n" +
	"\n" +
	"CampaignAd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1b.campaign.v1.CampaignTypeAdR\x04type\x12!\n" +
	"\fscheduled_at\x18\x06 \x01(\x03R\vscheduledAt\x12?\n" +
	"\n" +
	"ad_details\x18\a \x01(\v2\x1e.campaign.v1.CampaignDetailsAdH\x00R\tadDetails\x12J\n" +
	"\remail_details\x18\b \x01(\v2#.campaign.v1.EmailCampaignDetailsAdH\x00R\femailDetailsB\t\n" +
	"\adetails\"B\n" +
	"\x16CreateCampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"&\n" +
	"\x14GetCampaignAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x13GetCampaignResponse\x123\n" +
	"\bcampaign\x18\x01 \x01(\v2\x17.campaign.v1.CampaignAdR\bcampaign\"D\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\"0\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\\\n" +
	"\x0eCampaignTypeAd\x12\x1d\n" +
	"\x19CAMPAIGN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CAMPAIGN_TYPE_AD\x10\x01\x12\x15\n" +
	"\x11CAMPAIGN_TYPE_MTA\x10\x022\x99\x02\n" +
	"\x11CampaignServiceAd\x12[\n" +
	"\x0eCreateCampaign\x12$.campaign.v1.CreateCampaignRequestAd\x1a#.campaign.v1.CreateCampaignResponse\x12R\n" +
	"\vGetCampaign\x12!.campaign.v1.GetCampaignAdRequest\x1a .campaign.v1.GetCampaignResponse\x12S\n" +
	"\fUpdateStatus\x12 .campaign.v1.UpdateStatusRequest\x1a!.campaign.v1.UpdateStatusResponseB;Z9github.com/ehsanshah/empire-protos/campaign/v1;campaignv1b\x06proto3"

var (
	file_camp_v1_campaign_ad_proto_rawDescOnce sync.Once
	file_camp_v1_campaign_ad_proto_rawDescData []byte
)

func file_camp_v1_campaign_ad_proto_rawDescGZIP() []byte {
	file_camp_v1_campaign_ad_proto_rawDescOnce.Do(func() {
		file_camp_v1_campaign_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_camp_v1_campaign_ad_proto_rawDesc), len(file_camp_v1_campaign_ad_proto_rawDesc)))
	})
	return file_camp_v1_campaign_ad_proto_rawDescData
}

var file_camp_v1_campaign_ad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_camp_v1_campaign_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_camp_v1_campaign_ad_proto_goTypes = []any{
	(CampaignTypeAd)(0),             // 0: campaign.v1.CampaignTypeAd
	(*CampaignDetailsAd)(nil),       // 1: campaign.v1.CampaignDetailsAd
	(*EmailCampaignDetailsAd)(nil),  // 2: campaign.v1.EmailCampaignDetailsAd
	(*CreateCampaignRequestAd)(nil), // 3: campaign.v1.CreateCampaignRequestAd
	(*CampaignAd)(nil),              // 4: campaign.v1.CampaignAd
	(*CreateCampaignResponse)(nil),  // 5: campaign.v1.CreateCampaignResponse
	(*GetCampaignAdRequest)(nil),    // 6: campaign.v1.GetCampaignAdRequest
	(*GetCampaignResponse)(nil),     // 7: campaign.v1.GetCampaignResponse
	(*UpdateStatusRequest)(nil),     // 8: campaign.v1.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),    // 9: campaign.v1.UpdateStatusResponse
}
var file_camp_v1_campaign_ad_proto_depIdxs = []int32{
	1, // 0: campaign.v1.CreateCampaignRequestAd.ad_details:type_name -> campaign.v1.CampaignDetailsAd
	2, // 1: campaign.v1.CreateCampaignRequestAd.email_details:type_name -> campaign.v1.EmailCampaignDetailsAd
	0, // 2: campaign.v1.CampaignAd.type:type_name -> campaign.v1.CampaignTypeAd
	1, // 3: campaign.v1.CampaignAd.ad_details:type_name -> campaign.v1.CampaignDetailsAd
	2, // 4: campaign.v1.CampaignAd.email_details:type_name -> campaign.v1.EmailCampaignDetailsAd
	4, // 5: campaign.v1.GetCampaignResponse.campaign:type_name -> campaign.v1.CampaignAd
	3, // 6: campaign.v1.CampaignServiceAd.CreateCampaign:input_type -> campaign.v1.CreateCampaignRequestAd
	6, // 7: campaign.v1.CampaignServiceAd.GetCampaign:input_type -> campaign.v1.GetCampaignAdRequest
	8, // 8: campaign.v1.CampaignServiceAd.UpdateStatus:input_type -> campaign.v1.UpdateStatusRequest
	5, // 9: campaign.v1.CampaignServiceAd.CreateCampaign:output_type -> campaign.v1.CreateCampaignResponse
	7, // 10: campaign.v1.CampaignServiceAd.GetCampaign:output_type -> campaign.v1.GetCampaignResponse
	9, // 11: campaign.v1.CampaignServiceAd.UpdateStatus:output_type -> campaign.v1.UpdateStatusResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_camp_v1_campaign_ad_proto_init() }
func file_camp_v1_campaign_ad_proto_init() {
	if File_camp_v1_campaign_ad_proto != nil {
		return
	}
	file_camp_v1_campaign_ad_proto_msgTypes[2].OneofWrappers = []any{
		(*CreateCampaignRequestAd_AdDetails)(nil),
		(*CreateCampaignRequestAd_EmailDetails)(nil),
	}
	file_camp_v1_campaign_ad_proto_msgTypes[3].OneofWrappers = []any{
		(*CampaignAd_AdDetails)(nil),
		(*CampaignAd_EmailDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_camp_v1_campaign_ad_proto_rawDesc), len(file_camp_v1_campaign_ad_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camp_v1_campaign_ad_proto_goTypes,
		DependencyIndexes: file_camp_v1_campaign_ad_proto_depIdxs,
		EnumInfos:         file_camp_v1_campaign_ad_proto_enumTypes,
		MessageInfos:      file_camp_v1_campaign_ad_proto_msgTypes,
	}.Build()
	File_camp_v1_campaign_ad_proto = out.File
	file_camp_v1_campaign_ad_proto_goTypes = nil
	file_camp_v1_campaign_ad_proto_depIdxs = nil
}
