// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: camp/v1/campaign.proto

package campaignv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CampaignsMtaService_CreateCampaign_FullMethodName   = "/campaign.v1.CampaignsMtaService/CreateCampaign"
	CampaignsMtaService_ListCampaigns_FullMethodName    = "/campaign.v1.CampaignsMtaService/ListCampaigns"
	CampaignsMtaService_GetCampaign_FullMethodName      = "/campaign.v1.CampaignsMtaService/GetCampaign"
	CampaignsMtaService_UpdateCampaign_FullMethodName   = "/campaign.v1.CampaignsMtaService/UpdateCampaign"
	CampaignsMtaService_ScheduleCampaign_FullMethodName = "/campaign.v1.CampaignsMtaService/ScheduleCampaign"
	CampaignsMtaService_CancelCampaign_FullMethodName   = "/campaign.v1.CampaignsMtaService/CancelCampaign"
	CampaignsMtaService_DeleteCampaign_FullMethodName   = "/campaign.v1.CampaignsMtaService/DeleteCampaign"
)

// CampaignsMtaServiceClient is the client API for CampaignsMtaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignsMtaServiceClient interface {
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error)
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	ScheduleCampaign(ctx context.Context, in *ScheduleCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	CancelCampaign(ctx context.Context, in *CancelCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type campaignsMtaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignsMtaServiceClient(cc grpc.ClientConnInterface) CampaignsMtaServiceClient {
	return &campaignsMtaServiceClient{cc}
}

func (c *campaignsMtaServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) ScheduleCampaign(ctx context.Context, in *ScheduleCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_ScheduleCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) CancelCampaign(ctx context.Context, in *CancelCampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_CancelCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsMtaServiceClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CampaignsMtaService_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignsMtaServiceServer is the server API for CampaignsMtaService service.
// All implementations must embed UnimplementedCampaignsMtaServiceServer
// for forward compatibility.
type CampaignsMtaServiceServer interface {
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CampaignResponse, error)
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*CampaignResponse, error)
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*CampaignResponse, error)
	ScheduleCampaign(context.Context, *ScheduleCampaignRequest) (*CampaignResponse, error)
	CancelCampaign(context.Context, *CancelCampaignRequest) (*CampaignResponse, error)
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedCampaignsMtaServiceServer()
}

// UnimplementedCampaignsMtaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignsMtaServiceServer struct{}

func (UnimplementedCampaignsMtaServiceServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) GetCampaign(context.Context, *GetCampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) UpdateCampaign(context.Context, *UpdateCampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) ScheduleCampaign(context.Context, *ScheduleCampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) CancelCampaign(context.Context, *CancelCampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedCampaignsMtaServiceServer) mustEmbedUnimplementedCampaignsMtaServiceServer() {}
func (UnimplementedCampaignsMtaServiceServer) testEmbeddedByValue()                             {}

// UnsafeCampaignsMtaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignsMtaServiceServer will
// result in compilation errors.
type UnsafeCampaignsMtaServiceServer interface {
	mustEmbedUnimplementedCampaignsMtaServiceServer()
}

func RegisterCampaignsMtaServiceServer(s grpc.ServiceRegistrar, srv CampaignsMtaServiceServer) {
	// If the following call panics, it indicates UnimplementedCampaignsMtaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignsMtaService_ServiceDesc, srv)
}

func _CampaignsMtaService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_ScheduleCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).ScheduleCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_ScheduleCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).ScheduleCampaign(ctx, req.(*ScheduleCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_CancelCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).CancelCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_CancelCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).CancelCampaign(ctx, req.(*CancelCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsMtaService_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsMtaServiceServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsMtaService_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsMtaServiceServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignsMtaService_ServiceDesc is the grpc.ServiceDesc for CampaignsMtaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignsMtaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaign.v1.CampaignsMtaService",
	HandlerType: (*CampaignsMtaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignsMtaService_CreateCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _CampaignsMtaService_ListCampaigns_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _CampaignsMtaService_GetCampaign_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _CampaignsMtaService_UpdateCampaign_Handler,
		},
		{
			MethodName: "ScheduleCampaign",
			Handler:    _CampaignsMtaService_ScheduleCampaign_Handler,
		},
		{
			MethodName: "CancelCampaign",
			Handler:    _CampaignsMtaService_CancelCampaign_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _CampaignsMtaService_DeleteCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "camp/v1/campaign.proto",
}
