// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: camp/v1/campaign.proto

package campaignv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         float64                `protobuf:"fixed64,1,opt,name=float,proto3" json:"float,omitempty"`
	String_       string                 `protobuf:"bytes,2,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRate) Reset() {
	*x = StatsRate{}
	mi := &file_camp_v1_campaign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRate) ProtoMessage() {}

func (x *StatsRate) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRate.ProtoReflect.Descriptor instead.
func (*StatsRate) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *StatsRate) GetFloat() float64 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *StatsRate) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

type CampaignStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sent              int64                  `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	OpensCount        int64                  `protobuf:"varint,2,opt,name=opens_count,json=opensCount,proto3" json:"opens_count,omitempty"`
	UniqueOpensCount  int64                  `protobuf:"varint,3,opt,name=unique_opens_count,json=uniqueOpensCount,proto3" json:"unique_opens_count,omitempty"`
	OpenRate          *StatsRate             `protobuf:"bytes,4,opt,name=open_rate,json=openRate,proto3" json:"open_rate,omitempty"`
	ClicksCount       int64                  `protobuf:"varint,5,opt,name=clicks_count,json=clicksCount,proto3" json:"clicks_count,omitempty"`
	UniqueClicksCount int64                  `protobuf:"varint,6,opt,name=unique_clicks_count,json=uniqueClicksCount,proto3" json:"unique_clicks_count,omitempty"`
	ClickRate         *StatsRate             `protobuf:"bytes,7,opt,name=click_rate,json=clickRate,proto3" json:"click_rate,omitempty"`
	UnsubscribesCount int64                  `protobuf:"varint,8,opt,name=unsubscribes_count,json=unsubscribesCount,proto3" json:"unsubscribes_count,omitempty"`
	UnsubscribeRate   *StatsRate             `protobuf:"bytes,9,opt,name=unsubscribe_rate,json=unsubscribeRate,proto3" json:"unsubscribe_rate,omitempty"`
	SpamCount         int64                  `protobuf:"varint,10,opt,name=spam_count,json=spamCount,proto3" json:"spam_count,omitempty"`
	SpamRate          *StatsRate             `protobuf:"bytes,11,opt,name=spam_rate,json=spamRate,proto3" json:"spam_rate,omitempty"`
	HardBouncesCount  int64                  `protobuf:"varint,12,opt,name=hard_bounces_count,json=hardBouncesCount,proto3" json:"hard_bounces_count,omitempty"`
	HardBounceRate    *StatsRate             `protobuf:"bytes,13,opt,name=hard_bounce_rate,json=hardBounceRate,proto3" json:"hard_bounce_rate,omitempty"`
	SoftBouncesCount  int64                  `protobuf:"varint,14,opt,name=soft_bounces_count,json=softBouncesCount,proto3" json:"soft_bounces_count,omitempty"`
	SoftBounceRate    *StatsRate             `protobuf:"bytes,15,opt,name=soft_bounce_rate,json=softBounceRate,proto3" json:"soft_bounce_rate,omitempty"`
	DeliveryRate      float64                `protobuf:"fixed64,16,opt,name=delivery_rate,json=deliveryRate,proto3" json:"delivery_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CampaignStats) Reset() {
	*x = CampaignStats{}
	mi := &file_camp_v1_campaign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStats) ProtoMessage() {}

func (x *CampaignStats) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStats.ProtoReflect.Descriptor instead.
func (*CampaignStats) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignStats) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *CampaignStats) GetOpensCount() int64 {
	if x != nil {
		return x.OpensCount
	}
	return 0
}

func (x *CampaignStats) GetUniqueOpensCount() int64 {
	if x != nil {
		return x.UniqueOpensCount
	}
	return 0
}

func (x *CampaignStats) GetOpenRate() *StatsRate {
	if x != nil {
		return x.OpenRate
	}
	return nil
}

func (x *CampaignStats) GetClicksCount() int64 {
	if x != nil {
		return x.ClicksCount
	}
	return 0
}

func (x *CampaignStats) GetUniqueClicksCount() int64 {
	if x != nil {
		return x.UniqueClicksCount
	}
	return 0
}

func (x *CampaignStats) GetClickRate() *StatsRate {
	if x != nil {
		return x.ClickRate
	}
	return nil
}

func (x *CampaignStats) GetUnsubscribesCount() int64 {
	if x != nil {
		return x.UnsubscribesCount
	}
	return 0
}

func (x *CampaignStats) GetUnsubscribeRate() *StatsRate {
	if x != nil {
		return x.UnsubscribeRate
	}
	return nil
}

func (x *CampaignStats) GetSpamCount() int64 {
	if x != nil {
		return x.SpamCount
	}
	return 0
}

func (x *CampaignStats) GetSpamRate() *StatsRate {
	if x != nil {
		return x.SpamRate
	}
	return nil
}

func (x *CampaignStats) GetHardBouncesCount() int64 {
	if x != nil {
		return x.HardBouncesCount
	}
	return 0
}

func (x *CampaignStats) GetHardBounceRate() *StatsRate {
	if x != nil {
		return x.HardBounceRate
	}
	return nil
}

func (x *CampaignStats) GetSoftBouncesCount() int64 {
	if x != nil {
		return x.SoftBouncesCount
	}
	return 0
}

func (x *CampaignStats) GetSoftBounceRate() *StatsRate {
	if x != nil {
		return x.SoftBounceRate
	}
	return nil
}

func (x *CampaignStats) GetDeliveryRate() float64 {
	if x != nil {
		return x.DeliveryRate
	}
	return 0
}

type FilterCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Args          []*structpb.Value      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"` // استفاده از Value برای پشتیبانی از انواع دیتا (interface{})
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterCondition) Reset() {
	*x = FilterCondition{}
	mi := &file_camp_v1_campaign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCondition) ProtoMessage() {}

func (x *FilterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCondition.ProtoReflect.Descriptor instead.
func (*FilterCondition) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *FilterCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FilterCondition) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type CampaignOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeliveryOptimization string                 `protobuf:"bytes,1,opt,name=delivery_optimization,json=deliveryOptimization,proto3" json:"delivery_optimization,omitempty"`
	TrackOpens           bool                   `protobuf:"varint,2,opt,name=track_opens,json=trackOpens,proto3" json:"track_opens,omitempty"`
	TrackClicks          bool                   `protobuf:"varint,3,opt,name=track_clicks,json=trackClicks,proto3" json:"track_clicks,omitempty"`
	UseGoogleAnalytics   bool                   `protobuf:"varint,4,opt,name=use_google_analytics,json=useGoogleAnalytics,proto3" json:"use_google_analytics,omitempty"`
	EcommerceTracking    bool                   `protobuf:"varint,5,opt,name=ecommerce_tracking,json=ecommerceTracking,proto3" json:"ecommerce_tracking,omitempty"`
	TriggerFrequency     int32                  `protobuf:"varint,6,opt,name=trigger_frequency,json=triggerFrequency,proto3" json:"trigger_frequency,omitempty"`
	TriggerCount         int32                  `protobuf:"varint,7,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`
	UsesSurvey           bool                   `protobuf:"varint,8,opt,name=uses_survey,json=usesSurvey,proto3" json:"uses_survey,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CampaignOptions) Reset() {
	*x = CampaignOptions{}
	mi := &file_camp_v1_campaign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignOptions) ProtoMessage() {}

func (x *CampaignOptions) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignOptions.ProtoReflect.Descriptor instead.
func (*CampaignOptions) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{3}
}

func (x *CampaignOptions) GetDeliveryOptimization() string {
	if x != nil {
		return x.DeliveryOptimization
	}
	return ""
}

func (x *CampaignOptions) GetTrackOpens() bool {
	if x != nil {
		return x.TrackOpens
	}
	return false
}

func (x *CampaignOptions) GetTrackClicks() bool {
	if x != nil {
		return x.TrackClicks
	}
	return false
}

func (x *CampaignOptions) GetUseGoogleAnalytics() bool {
	if x != nil {
		return x.UseGoogleAnalytics
	}
	return false
}

func (x *CampaignOptions) GetEcommerceTracking() bool {
	if x != nil {
		return x.EcommerceTracking
	}
	return false
}

func (x *CampaignOptions) GetTriggerFrequency() int32 {
	if x != nil {
		return x.TriggerFrequency
	}
	return 0
}

func (x *CampaignOptions) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *CampaignOptions) GetUsesSurvey() bool {
	if x != nil {
		return x.UsesSurvey
	}
	return false
}

type CampaignRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListIds       []string               `protobuf:"bytes,1,rep,name=list_ids,json=listIds,proto3" json:"list_ids,omitempty"`
	SegmentIds    []string               `protobuf:"bytes,2,rep,name=segment_ids,json=segmentIds,proto3" json:"segment_ids,omitempty"`
	ListNames     []string               `protobuf:"bytes,3,rep,name=list_names,json=listNames,proto3" json:"list_names,omitempty"`
	SegmentNames  []string               `protobuf:"bytes,4,rep,name=segment_names,json=segmentNames,proto3" json:"segment_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignRecipient) Reset() {
	*x = CampaignRecipient{}
	mi := &file_camp_v1_campaign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignRecipient) ProtoMessage() {}

func (x *CampaignRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignRecipient.ProtoReflect.Descriptor instead.
func (*CampaignRecipient) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{4}
}

func (x *CampaignRecipient) GetListIds() []string {
	if x != nil {
		return x.ListIds
	}
	return nil
}

func (x *CampaignRecipient) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

func (x *CampaignRecipient) GetListNames() []string {
	if x != nil {
		return x.ListNames
	}
	return nil
}

func (x *CampaignRecipient) GetSegmentNames() []string {
	if x != nil {
		return x.SegmentNames
	}
	return nil
}

type Campaign struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId                  string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status                     string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TypeForHumans              string                 `protobuf:"bytes,5,opt,name=type_for_humans,json=typeForHumans,proto3" json:"type_for_humans,omitempty"`
	Recipients                 *CampaignRecipient     `protobuf:"bytes,6,opt,name=recipients,proto3" json:"recipients,omitempty"`
	Options                    *CampaignOptions       `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	Stats                      *CampaignStats         `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	Filters                    []*FilterCondition     `protobuf:"bytes,9,rep,name=filters,proto3" json:"filters,omitempty"` // فیلترها کاملاً لحاظ شد
	CreatedAt                  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ScheduledFor               *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	QueuedAt                   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	StartedAt                  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt                 *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	StoppedAt                  *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	WinnerSelectedAt           *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=winner_selected_at,json=winnerSelectedAt,proto3" json:"winner_selected_at,omitempty"`
	IsStopped                  bool                   `protobuf:"varint,18,opt,name=is_stopped,json=isStopped,proto3" json:"is_stopped,omitempty"`
	IsCurrentlySendingOut      bool                   `protobuf:"varint,19,opt,name=is_currently_sending_out,json=isCurrentlySendingOut,proto3" json:"is_currently_sending_out,omitempty"`
	CanBeScheduled             bool                   `protobuf:"varint,20,opt,name=can_be_scheduled,json=canBeScheduled,proto3" json:"can_be_scheduled,omitempty"`
	HasWinner                  bool                   `protobuf:"varint,21,opt,name=has_winner,json=hasWinner,proto3" json:"has_winner,omitempty"`
	WinnerVersionForHuman      string                 `protobuf:"bytes,22,opt,name=winner_version_for_human,json=winnerVersionForHuman,proto3" json:"winner_version_for_human,omitempty"`
	WinnerSendingTimeForHumans string                 `protobuf:"bytes,23,opt,name=winner_sending_time_for_humans,json=winnerSendingTimeForHumans,proto3" json:"winner_sending_time_for_humans,omitempty"`
	EmailIds                   []string               `protobuf:"bytes,24,rep,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	DefaultEmailId             string                 `protobuf:"bytes,25,opt,name=default_email_id,json=defaultEmailId,proto3" json:"default_email_id,omitempty"`
	Warnings                   []string               `protobuf:"bytes,26,rep,name=warnings,proto3" json:"warnings,omitempty"`
	UsedInAutomations          bool                   `protobuf:"varint,27,opt,name=used_in_automations,json=usedInAutomations,proto3" json:"used_in_automations,omitempty"`
	ExtraFields                *structpb.Struct       `protobuf:"bytes,28,opt,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"` // فیلد منعطف برای دیتای اضافه
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_camp_v1_campaign_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{5}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetTypeForHumans() string {
	if x != nil {
		return x.TypeForHumans
	}
	return ""
}

func (x *Campaign) GetRecipients() *CampaignRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *Campaign) GetOptions() *CampaignOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Campaign) GetStats() *CampaignStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Campaign) GetFilters() []*FilterCondition {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Campaign) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Campaign) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *Campaign) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *Campaign) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Campaign) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Campaign) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *Campaign) GetWinnerSelectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WinnerSelectedAt
	}
	return nil
}

func (x *Campaign) GetIsStopped() bool {
	if x != nil {
		return x.IsStopped
	}
	return false
}

func (x *Campaign) GetIsCurrentlySendingOut() bool {
	if x != nil {
		return x.IsCurrentlySendingOut
	}
	return false
}

func (x *Campaign) GetCanBeScheduled() bool {
	if x != nil {
		return x.CanBeScheduled
	}
	return false
}

func (x *Campaign) GetHasWinner() bool {
	if x != nil {
		return x.HasWinner
	}
	return false
}

func (x *Campaign) GetWinnerVersionForHuman() string {
	if x != nil {
		return x.WinnerVersionForHuman
	}
	return ""
}

func (x *Campaign) GetWinnerSendingTimeForHumans() string {
	if x != nil {
		return x.WinnerSendingTimeForHumans
	}
	return ""
}

func (x *Campaign) GetEmailIds() []string {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

func (x *Campaign) GetDefaultEmailId() string {
	if x != nil {
		return x.DefaultEmailId
	}
	return ""
}

func (x *Campaign) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *Campaign) GetUsedInAutomations() bool {
	if x != nil {
		return x.UsedInAutomations
	}
	return false
}

func (x *Campaign) GetExtraFields() *structpb.Struct {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Recipients    *CampaignRecipient     `protobuf:"bytes,3,opt,name=recipients,proto3" json:"recipients,omitempty"`
	EmailIds      []string               `protobuf:"bytes,4,rep,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	Options       *CampaignOptions       `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetRecipients() *CampaignRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *CreateCampaignRequest) GetEmailIds() []string {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

func (x *CreateCampaignRequest) GetOptions() *CampaignOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Campaign      *Campaign              `protobuf:"bytes,3,opt,name=campaign,proto3" json:"campaign,omitempty"` // شامل تمامی فیلترها و تنظیمات جدید
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateCampaignRequest) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type CampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignResponse) Reset() {
	*x = CampaignResponse{}
	mi := &file_camp_v1_campaign_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignResponse) ProtoMessage() {}

func (x *CampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignResponse.ProtoReflect.Descriptor instead.
func (*CampaignResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{8}
}

func (x *CampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // اضافه شد
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // اضافه شد
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{9}
}

func (x *ListCampaignsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListCampaignsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCampaignsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_camp_v1_campaign_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{10}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{11}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ScheduleCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SendAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleCampaignRequest) Reset() {
	*x = ScheduleCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCampaignRequest) ProtoMessage() {}

func (x *ScheduleCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCampaignRequest.ProtoReflect.Descriptor instead.
func (*ScheduleCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ScheduleCampaignRequest) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

type CancelCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCampaignRequest) Reset() {
	*x = CancelCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCampaignRequest) ProtoMessage() {}

func (x *CancelCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCampaignRequest.ProtoReflect.Descriptor instead.
func (*CancelCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{13}
}

func (x *CancelCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_camp_v1_campaign_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCampaignRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_camp_v1_campaign_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camp_v1_campaign_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_camp_v1_campaign_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_camp_v1_campaign_proto protoreflect.FileDescriptor

const file_camp_v1_campaign_proto_rawDesc = "" +
	"\n" +
	"\x16camp/v1/campaign.proto\x12\vcampaign.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"9\n" +
	"\tStatsRate\x12\x14\n" +
	"\x05float\x18\x01 \x01(\x01R\x05float\x12\x16\n" +
	"\x06string\x18\x02 \x01(\tR\x06string\"\xfc\x05\n" +
	"\rCampaignStats\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\x03R\x04sent\x12\x1f\n" +
	"\vopens_count\x18\x02 \x01(\x03R\n" +
	"opensCount\x12,\n" +
	"\x12unique_opens_count\x18\x03 \x01(\x03R\x10uniqueOpensCount\x123\n" +
	"\topen_rate\x18\x04 \x01(\v2\x16.campaign.v1.StatsRateR\bopenRate\x12!\n" +
	"\fclicks_count\x18\x05 \x01(\x03R\vclicksCount\x12.\n" +
	"\x13unique_clicks_count\x18\x06 \x01(\x03R\x11uniqueClicksCount\x125\n" +
	"\n" +
	"click_rate\x18\a \x01(\v2\x16.campaign.v1.StatsRateR\tclickRate\x12-\n" +
	"\x12unsubscribes_count\x18\b \x01(\x03R\x11unsubscribesCount\x12A\n" +
	"\x10unsubscribe_rate\x18\t \x01(\v2\x16.campaign.v1.StatsRateR\x0funsubscribeRate\x12\x1d\n" +
	"\n" +
	"spam_count\x18\n" +
	" \x01(\x03R\tspamCount\x123\n" +
	"\tspam_rate\x18\v \x01(\v2\x16.campaign.v1.StatsRateR\bspamRate\x12,\n" +
	"\x12hard_bounces_count\x18\f \x01(\x03R\x10hardBouncesCount\x12@\n" +
	"\x10hard_bounce_rate\x18\r \x01(\v2\x16.campaign.v1.StatsRateR\x0ehardBounceRate\x12,\n" +
	"\x12soft_bounces_count\x18\x0e \x01(\x03R\x10softBouncesCount\x12@\n" +
	"\x10soft_bounce_rate\x18\x0f \x01(\v2\x16.campaign.v1.StatsRateR\x0esoftBounceRate\x12#\n" +
	"\rdelivery_rate\x18\x10 \x01(\x01R\fdeliveryRate\"Y\n" +
	"\x0fFilterCondition\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12*\n" +
	"\x04args\x18\x02 \x03(\v2\x16.google.protobuf.ValueR\x04args\"\xde\x02\n" +
	"\x0fCampaignOptions\x123\n" +
	"\x15delivery_optimization\x18\x01 \x01(\tR\x14deliveryOptimization\x12\x1f\n" +
	"\vtrack_opens\x18\x02 \x01(\bR\n" +
	"trackOpens\x12!\n" +
	"\ftrack_clicks\x18\x03 \x01(\bR\vtrackClicks\x120\n" +
	"\x14use_google_analytics\x18\x04 \x01(\bR\x12useGoogleAnalytics\x12-\n" +
	"\x12ecommerce_tracking\x18\x05 \x01(\bR\x11ecommerceTracking\x12+\n" +
	"\x11trigger_frequency\x18\x06 \x01(\x05R\x10triggerFrequency\x12#\n" +
	"\rtrigger_count\x18\a \x01(\x05R\ftriggerCount\x12\x1f\n" +
	"\vuses_survey\x18\b \x01(\bR\n" +
	"usesSurvey\"\x93\x01\n" +
	"\x11CampaignRecipient\x12\x19\n" +
	"\blist_ids\x18\x01 \x03(\tR\alistIds\x12\x1f\n" +
	"\vsegment_ids\x18\x02 \x03(\tR\n" +
	"segmentIds\x12\x1d\n" +
	"\n" +
	"list_names\x18\x03 \x03(\tR\tlistNames\x12#\n" +
	"\rsegment_names\x18\x04 \x03(\tR\fsegmentNames\"\xc9\n" +
	"\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0ftype_for_humans\x18\x05 \x01(\tR\rtypeForHumans\x12>\n" +
	"\n" +
	"recipients\x18\x06 \x01(\v2\x1e.campaign.v1.CampaignRecipientR\n" +
	"recipients\x126\n" +
	"\aoptions\x18\a \x01(\v2\x1c.campaign.v1.CampaignOptionsR\aoptions\x120\n" +
	"\x05stats\x18\b \x01(\v2\x1a.campaign.v1.CampaignStatsR\x05stats\x126\n" +
	"\afilters\x18\t \x03(\v2\x1c.campaign.v1.FilterConditionR\afilters\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12?\n" +
	"\rscheduled_for\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x127\n" +
	"\tqueued_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x129\n" +
	"\n" +
	"stopped_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x12H\n" +
	"\x12winner_selected_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x10winnerSelectedAt\x12\x1d\n" +
	"\n" +
	"is_stopped\x18\x12 \x01(\bR\tisStopped\x127\n" +
	"\x18is_currently_sending_out\x18\x13 \x01(\bR\x15isCurrentlySendingOut\x12(\n" +
	"\x10can_be_scheduled\x18\x14 \x01(\bR\x0ecanBeScheduled\x12\x1d\n" +
	"\n" +
	"has_winner\x18\x15 \x01(\bR\thasWinner\x127\n" +
	"\x18winner_version_for_human\x18\x16 \x01(\tR\x15winnerVersionForHuman\x12B\n" +
	"\x1ewinner_sending_time_for_humans\x18\x17 \x01(\tR\x1awinnerSendingTimeForHumans\x12\x1b\n" +
	"\temail_ids\x18\x18 \x03(\tR\bemailIds\x12(\n" +
	"\x10default_email_id\x18\x19 \x01(\tR\x0edefaultEmailId\x12\x1a\n" +
	"\bwarnings\x18\x1a \x03(\tR\bwarnings\x12.\n" +
	"\x13used_in_automations\x18\x1b \x01(\bR\x11usedInAutomations\x12:\n" +
	"\fextra_fields\x18\x1c \x01(\v2\x17.google.protobuf.StructR\vextraFields\"\xdf\x01\n" +
	"\x15CreateCampaignRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\n" +
	"recipients\x18\x03 \x01(\v2\x1e.campaign.v1.CampaignRecipientR\n" +
	"recipients\x12\x1b\n" +
	"\temail_ids\x18\x04 \x03(\tR\bemailIds\x126\n" +
	"\aoptions\x18\x05 \x01(\v2\x1c.campaign.v1.CampaignOptionsR\aoptions\"y\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x121\n" +
	"\bcampaign\x18\x03 \x01(\v2\x15.campaign.v1.CampaignR\bcampaign\"E\n" +
	"\x10CampaignResponse\x121\n" +
	"\bcampaign\x18\x01 \x01(\v2\x15.campaign.v1.CampaignR\bcampaign\"c\n" +
	"\x14ListCampaignsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"L\n" +
	"\x15ListCampaignsResponse\x123\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x15.campaign.v1.CampaignR\tcampaigns\"C\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"}\n" +
	"\x17ScheduleCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x123\n" +
	"\asend_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\"F\n" +
	"\x15CancelCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"F\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe7\x04\n" +
	"\x13CampaignsMtaService\x12S\n" +
	"\x0eCreateCampaign\x12\".campaign.v1.CreateCampaignRequest\x1a\x1d.campaign.v1.CampaignResponse\x12V\n" +
	"\rListCampaigns\x12!.campaign.v1.ListCampaignsRequest\x1a\".campaign.v1.ListCampaignsResponse\x12M\n" +
	"\vGetCampaign\x12\x1f.campaign.v1.GetCampaignRequest\x1a\x1d.campaign.v1.CampaignResponse\x12S\n" +
	"\x0eUpdateCampaign\x12\".campaign.v1.UpdateCampaignRequest\x1a\x1d.campaign.v1.CampaignResponse\x12W\n" +
	"\x10ScheduleCampaign\x12$.campaign.v1.ScheduleCampaignRequest\x1a\x1d.campaign.v1.CampaignResponse\x12S\n" +
	"\x0eCancelCampaign\x12\".campaign.v1.CancelCampaignRequest\x1a\x1d.campaign.v1.CampaignResponse\x12Q\n" +
	"\x0eDeleteCampaign\x12\".campaign.v1.DeleteCampaignRequest\x1a\x1b.campaign.v1.DeleteResponseB;Z9github.com/ehsanshah/empire-protos/campaign/v1;campaignv1b\x06proto3"

var (
	file_camp_v1_campaign_proto_rawDescOnce sync.Once
	file_camp_v1_campaign_proto_rawDescData []byte
)

func file_camp_v1_campaign_proto_rawDescGZIP() []byte {
	file_camp_v1_campaign_proto_rawDescOnce.Do(func() {
		file_camp_v1_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_camp_v1_campaign_proto_rawDesc), len(file_camp_v1_campaign_proto_rawDesc)))
	})
	return file_camp_v1_campaign_proto_rawDescData
}

var file_camp_v1_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_camp_v1_campaign_proto_goTypes = []any{
	(*StatsRate)(nil),               // 0: campaign.v1.StatsRate
	(*CampaignStats)(nil),           // 1: campaign.v1.CampaignStats
	(*FilterCondition)(nil),         // 2: campaign.v1.FilterCondition
	(*CampaignOptions)(nil),         // 3: campaign.v1.CampaignOptions
	(*CampaignRecipient)(nil),       // 4: campaign.v1.CampaignRecipient
	(*Campaign)(nil),                // 5: campaign.v1.Campaign
	(*CreateCampaignRequest)(nil),   // 6: campaign.v1.CreateCampaignRequest
	(*UpdateCampaignRequest)(nil),   // 7: campaign.v1.UpdateCampaignRequest
	(*CampaignResponse)(nil),        // 8: campaign.v1.CampaignResponse
	(*ListCampaignsRequest)(nil),    // 9: campaign.v1.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),   // 10: campaign.v1.ListCampaignsResponse
	(*GetCampaignRequest)(nil),      // 11: campaign.v1.GetCampaignRequest
	(*ScheduleCampaignRequest)(nil), // 12: campaign.v1.ScheduleCampaignRequest
	(*CancelCampaignRequest)(nil),   // 13: campaign.v1.CancelCampaignRequest
	(*DeleteCampaignRequest)(nil),   // 14: campaign.v1.DeleteCampaignRequest
	(*DeleteResponse)(nil),          // 15: campaign.v1.DeleteResponse
	(*structpb.Value)(nil),          // 16: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),   // 17: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 18: google.protobuf.Struct
}
var file_camp_v1_campaign_proto_depIdxs = []int32{
	0,  // 0: campaign.v1.CampaignStats.open_rate:type_name -> campaign.v1.StatsRate
	0,  // 1: campaign.v1.CampaignStats.click_rate:type_name -> campaign.v1.StatsRate
	0,  // 2: campaign.v1.CampaignStats.unsubscribe_rate:type_name -> campaign.v1.StatsRate
	0,  // 3: campaign.v1.CampaignStats.spam_rate:type_name -> campaign.v1.StatsRate
	0,  // 4: campaign.v1.CampaignStats.hard_bounce_rate:type_name -> campaign.v1.StatsRate
	0,  // 5: campaign.v1.CampaignStats.soft_bounce_rate:type_name -> campaign.v1.StatsRate
	16, // 6: campaign.v1.FilterCondition.args:type_name -> google.protobuf.Value
	4,  // 7: campaign.v1.Campaign.recipients:type_name -> campaign.v1.CampaignRecipient
	3,  // 8: campaign.v1.Campaign.options:type_name -> campaign.v1.CampaignOptions
	1,  // 9: campaign.v1.Campaign.stats:type_name -> campaign.v1.CampaignStats
	2,  // 10: campaign.v1.Campaign.filters:type_name -> campaign.v1.FilterCondition
	17, // 11: campaign.v1.Campaign.created_at:type_name -> google.protobuf.Timestamp
	17, // 12: campaign.v1.Campaign.updated_at:type_name -> google.protobuf.Timestamp
	17, // 13: campaign.v1.Campaign.scheduled_for:type_name -> google.protobuf.Timestamp
	17, // 14: campaign.v1.Campaign.queued_at:type_name -> google.protobuf.Timestamp
	17, // 15: campaign.v1.Campaign.started_at:type_name -> google.protobuf.Timestamp
	17, // 16: campaign.v1.Campaign.finished_at:type_name -> google.protobuf.Timestamp
	17, // 17: campaign.v1.Campaign.stopped_at:type_name -> google.protobuf.Timestamp
	17, // 18: campaign.v1.Campaign.winner_selected_at:type_name -> google.protobuf.Timestamp
	18, // 19: campaign.v1.Campaign.extra_fields:type_name -> google.protobuf.Struct
	4,  // 20: campaign.v1.CreateCampaignRequest.recipients:type_name -> campaign.v1.CampaignRecipient
	3,  // 21: campaign.v1.CreateCampaignRequest.options:type_name -> campaign.v1.CampaignOptions
	5,  // 22: campaign.v1.UpdateCampaignRequest.campaign:type_name -> campaign.v1.Campaign
	5,  // 23: campaign.v1.CampaignResponse.campaign:type_name -> campaign.v1.Campaign
	5,  // 24: campaign.v1.ListCampaignsResponse.campaigns:type_name -> campaign.v1.Campaign
	17, // 25: campaign.v1.ScheduleCampaignRequest.send_at:type_name -> google.protobuf.Timestamp
	6,  // 26: campaign.v1.CampaignsMtaService.CreateCampaign:input_type -> campaign.v1.CreateCampaignRequest
	9,  // 27: campaign.v1.CampaignsMtaService.ListCampaigns:input_type -> campaign.v1.ListCampaignsRequest
	11, // 28: campaign.v1.CampaignsMtaService.GetCampaign:input_type -> campaign.v1.GetCampaignRequest
	7,  // 29: campaign.v1.CampaignsMtaService.UpdateCampaign:input_type -> campaign.v1.UpdateCampaignRequest
	12, // 30: campaign.v1.CampaignsMtaService.ScheduleCampaign:input_type -> campaign.v1.ScheduleCampaignRequest
	13, // 31: campaign.v1.CampaignsMtaService.CancelCampaign:input_type -> campaign.v1.CancelCampaignRequest
	14, // 32: campaign.v1.CampaignsMtaService.DeleteCampaign:input_type -> campaign.v1.DeleteCampaignRequest
	8,  // 33: campaign.v1.CampaignsMtaService.CreateCampaign:output_type -> campaign.v1.CampaignResponse
	10, // 34: campaign.v1.CampaignsMtaService.ListCampaigns:output_type -> campaign.v1.ListCampaignsResponse
	8,  // 35: campaign.v1.CampaignsMtaService.GetCampaign:output_type -> campaign.v1.CampaignResponse
	8,  // 36: campaign.v1.CampaignsMtaService.UpdateCampaign:output_type -> campaign.v1.CampaignResponse
	8,  // 37: campaign.v1.CampaignsMtaService.ScheduleCampaign:output_type -> campaign.v1.CampaignResponse
	8,  // 38: campaign.v1.CampaignsMtaService.CancelCampaign:output_type -> campaign.v1.CampaignResponse
	15, // 39: campaign.v1.CampaignsMtaService.DeleteCampaign:output_type -> campaign.v1.DeleteResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_camp_v1_campaign_proto_init() }
func file_camp_v1_campaign_proto_init() {
	if File_camp_v1_campaign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_camp_v1_campaign_proto_rawDesc), len(file_camp_v1_campaign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camp_v1_campaign_proto_goTypes,
		DependencyIndexes: file_camp_v1_campaign_proto_depIdxs,
		MessageInfos:      file_camp_v1_campaign_proto_msgTypes,
	}.Build()
	File_camp_v1_campaign_proto = out.File
	file_camp_v1_campaign_proto_goTypes = nil
	file_camp_v1_campaign_proto_depIdxs = nil
}
