// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: camp/v1/template.proto

package campaignv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ITemplateServices_CreateTemplate_FullMethodName        = "/campaign.v1.ITemplateServices/CreateTemplate"
	ITemplateServices_UpdateTemplate_FullMethodName        = "/campaign.v1.ITemplateServices/UpdateTemplate"
	ITemplateServices_ListTemplates_FullMethodName         = "/campaign.v1.ITemplateServices/ListTemplates"
	ITemplateServices_CopyTemplate_FullMethodName          = "/campaign.v1.ITemplateServices/CopyTemplate"
	ITemplateServices_ImportTemplateFromUrl_FullMethodName = "/campaign.v1.ITemplateServices/ImportTemplateFromUrl"
	ITemplateServices_TestTemplate_FullMethodName          = "/campaign.v1.ITemplateServices/TestTemplate"
)

// ITemplateServicesClient is the client API for ITemplateServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ITemplateServicesClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	CopyTemplate(ctx context.Context, in *CopyTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	ImportTemplateFromUrl(ctx context.Context, in *ImportTemplateFromUrlRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	TestTemplate(ctx context.Context, in *TestTemplateRequest, opts ...grpc.CallOption) (*TestTemplateResponse, error)
}

type iTemplateServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewITemplateServicesClient(cc grpc.ClientConnInterface) ITemplateServicesClient {
	return &iTemplateServicesClient{cc}
}

func (c *iTemplateServicesClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTemplateServicesClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTemplateServicesClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTemplateServicesClient) CopyTemplate(ctx context.Context, in *CopyTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_CopyTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTemplateServicesClient) ImportTemplateFromUrl(ctx context.Context, in *ImportTemplateFromUrlRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_ImportTemplateFromUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTemplateServicesClient) TestTemplate(ctx context.Context, in *TestTemplateRequest, opts ...grpc.CallOption) (*TestTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestTemplateResponse)
	err := c.cc.Invoke(ctx, ITemplateServices_TestTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITemplateServicesServer is the server API for ITemplateServices service.
// All implementations must embed UnimplementedITemplateServicesServer
// for forward compatibility.
type ITemplateServicesServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	CopyTemplate(context.Context, *CopyTemplateRequest) (*TemplateResponse, error)
	ImportTemplateFromUrl(context.Context, *ImportTemplateFromUrlRequest) (*TemplateResponse, error)
	TestTemplate(context.Context, *TestTemplateRequest) (*TestTemplateResponse, error)
	mustEmbedUnimplementedITemplateServicesServer()
}

// UnimplementedITemplateServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedITemplateServicesServer struct{}

func (UnimplementedITemplateServicesServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedITemplateServicesServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedITemplateServicesServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedITemplateServicesServer) CopyTemplate(context.Context, *CopyTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyTemplate not implemented")
}
func (UnimplementedITemplateServicesServer) ImportTemplateFromUrl(context.Context, *ImportTemplateFromUrlRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportTemplateFromUrl not implemented")
}
func (UnimplementedITemplateServicesServer) TestTemplate(context.Context, *TestTemplateRequest) (*TestTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestTemplate not implemented")
}
func (UnimplementedITemplateServicesServer) mustEmbedUnimplementedITemplateServicesServer() {}
func (UnimplementedITemplateServicesServer) testEmbeddedByValue()                           {}

// UnsafeITemplateServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ITemplateServicesServer will
// result in compilation errors.
type UnsafeITemplateServicesServer interface {
	mustEmbedUnimplementedITemplateServicesServer()
}

func RegisterITemplateServicesServer(s grpc.ServiceRegistrar, srv ITemplateServicesServer) {
	// If the following call panics, it indicates UnimplementedITemplateServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ITemplateServices_ServiceDesc, srv)
}

func _ITemplateServices_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITemplateServices_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITemplateServices_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITemplateServices_CopyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).CopyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_CopyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).CopyTemplate(ctx, req.(*CopyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITemplateServices_ImportTemplateFromUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportTemplateFromUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).ImportTemplateFromUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_ImportTemplateFromUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).ImportTemplateFromUrl(ctx, req.(*ImportTemplateFromUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITemplateServices_TestTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITemplateServicesServer).TestTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITemplateServices_TestTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITemplateServicesServer).TestTemplate(ctx, req.(*TestTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ITemplateServices_ServiceDesc is the grpc.ServiceDesc for ITemplateServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ITemplateServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaign.v1.ITemplateServices",
	HandlerType: (*ITemplateServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _ITemplateServices_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _ITemplateServices_UpdateTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _ITemplateServices_ListTemplates_Handler,
		},
		{
			MethodName: "CopyTemplate",
			Handler:    _ITemplateServices_CopyTemplate_Handler,
		},
		{
			MethodName: "ImportTemplateFromUrl",
			Handler:    _ITemplateServices_ImportTemplateFromUrl_Handler,
		},
		{
			MethodName: "TestTemplate",
			Handler:    _ITemplateServices_TestTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "camp/v1/template.proto",
}
