// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: dispatcher/v1/email_scheduler_dispatcher.proto

package emailschedulerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailSchedulerDispatcher_ScheduleEmailCampaign_FullMethodName    = "/emailscheduler.EmailSchedulerDispatcher/ScheduleEmailCampaign"
	EmailSchedulerDispatcher_CancelScheduledEmail_FullMethodName     = "/emailscheduler.EmailSchedulerDispatcher/CancelScheduledEmail"
	EmailSchedulerDispatcher_DispatchEmailImmediately_FullMethodName = "/emailscheduler.EmailSchedulerDispatcher/DispatchEmailImmediately"
)

// EmailSchedulerDispatcherClient is the client API for EmailSchedulerDispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// مدیریت زمان‌بندی و dispatch ایمیل
type EmailSchedulerDispatcherClient interface {
	// فعال‌سازی زمان‌بندی یک کمپین
	ScheduleEmailCampaign(ctx context.Context, in *ScheduleEmailRequest, opts ...grpc.CallOption) (*ScheduleEmailResponse, error)
	// لغو یک کمپین زمان‌بندی‌شده
	CancelScheduledEmail(ctx context.Context, in *CancelScheduledEmailRequest, opts ...grpc.CallOption) (*CancelScheduledEmailResponse, error)
	// ارسال فوری ایمیل بدون زمان‌بندی
	DispatchEmailImmediately(ctx context.Context, in *DispatchEmailRequest, opts ...grpc.CallOption) (*DispatchEmailResponse, error)
}

type emailSchedulerDispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailSchedulerDispatcherClient(cc grpc.ClientConnInterface) EmailSchedulerDispatcherClient {
	return &emailSchedulerDispatcherClient{cc}
}

func (c *emailSchedulerDispatcherClient) ScheduleEmailCampaign(ctx context.Context, in *ScheduleEmailRequest, opts ...grpc.CallOption) (*ScheduleEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleEmailResponse)
	err := c.cc.Invoke(ctx, EmailSchedulerDispatcher_ScheduleEmailCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailSchedulerDispatcherClient) CancelScheduledEmail(ctx context.Context, in *CancelScheduledEmailRequest, opts ...grpc.CallOption) (*CancelScheduledEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelScheduledEmailResponse)
	err := c.cc.Invoke(ctx, EmailSchedulerDispatcher_CancelScheduledEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailSchedulerDispatcherClient) DispatchEmailImmediately(ctx context.Context, in *DispatchEmailRequest, opts ...grpc.CallOption) (*DispatchEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchEmailResponse)
	err := c.cc.Invoke(ctx, EmailSchedulerDispatcher_DispatchEmailImmediately_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailSchedulerDispatcherServer is the server API for EmailSchedulerDispatcher service.
// All implementations must embed UnimplementedEmailSchedulerDispatcherServer
// for forward compatibility.
//
// مدیریت زمان‌بندی و dispatch ایمیل
type EmailSchedulerDispatcherServer interface {
	// فعال‌سازی زمان‌بندی یک کمپین
	ScheduleEmailCampaign(context.Context, *ScheduleEmailRequest) (*ScheduleEmailResponse, error)
	// لغو یک کمپین زمان‌بندی‌شده
	CancelScheduledEmail(context.Context, *CancelScheduledEmailRequest) (*CancelScheduledEmailResponse, error)
	// ارسال فوری ایمیل بدون زمان‌بندی
	DispatchEmailImmediately(context.Context, *DispatchEmailRequest) (*DispatchEmailResponse, error)
	mustEmbedUnimplementedEmailSchedulerDispatcherServer()
}

// UnimplementedEmailSchedulerDispatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailSchedulerDispatcherServer struct{}

func (UnimplementedEmailSchedulerDispatcherServer) ScheduleEmailCampaign(context.Context, *ScheduleEmailRequest) (*ScheduleEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleEmailCampaign not implemented")
}
func (UnimplementedEmailSchedulerDispatcherServer) CancelScheduledEmail(context.Context, *CancelScheduledEmailRequest) (*CancelScheduledEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelScheduledEmail not implemented")
}
func (UnimplementedEmailSchedulerDispatcherServer) DispatchEmailImmediately(context.Context, *DispatchEmailRequest) (*DispatchEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchEmailImmediately not implemented")
}
func (UnimplementedEmailSchedulerDispatcherServer) mustEmbedUnimplementedEmailSchedulerDispatcherServer() {
}
func (UnimplementedEmailSchedulerDispatcherServer) testEmbeddedByValue() {}

// UnsafeEmailSchedulerDispatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailSchedulerDispatcherServer will
// result in compilation errors.
type UnsafeEmailSchedulerDispatcherServer interface {
	mustEmbedUnimplementedEmailSchedulerDispatcherServer()
}

func RegisterEmailSchedulerDispatcherServer(s grpc.ServiceRegistrar, srv EmailSchedulerDispatcherServer) {
	// If the following call panics, it indicates UnimplementedEmailSchedulerDispatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailSchedulerDispatcher_ServiceDesc, srv)
}

func _EmailSchedulerDispatcher_ScheduleEmailCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailSchedulerDispatcherServer).ScheduleEmailCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailSchedulerDispatcher_ScheduleEmailCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailSchedulerDispatcherServer).ScheduleEmailCampaign(ctx, req.(*ScheduleEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailSchedulerDispatcher_CancelScheduledEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelScheduledEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailSchedulerDispatcherServer).CancelScheduledEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailSchedulerDispatcher_CancelScheduledEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailSchedulerDispatcherServer).CancelScheduledEmail(ctx, req.(*CancelScheduledEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailSchedulerDispatcher_DispatchEmailImmediately_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailSchedulerDispatcherServer).DispatchEmailImmediately(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailSchedulerDispatcher_DispatchEmailImmediately_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailSchedulerDispatcherServer).DispatchEmailImmediately(ctx, req.(*DispatchEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailSchedulerDispatcher_ServiceDesc is the grpc.ServiceDesc for EmailSchedulerDispatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailSchedulerDispatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emailscheduler.EmailSchedulerDispatcher",
	HandlerType: (*EmailSchedulerDispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleEmailCampaign",
			Handler:    _EmailSchedulerDispatcher_ScheduleEmailCampaign_Handler,
		},
		{
			MethodName: "CancelScheduledEmail",
			Handler:    _EmailSchedulerDispatcher_CancelScheduledEmail_Handler,
		},
		{
			MethodName: "DispatchEmailImmediately",
			Handler:    _EmailSchedulerDispatcher_DispatchEmailImmediately_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatcher/v1/email_scheduler_dispatcher.proto",
}
