// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: dispatcher/v1/email_scheduler_dispatcher.proto

package emailschedulerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ScheduleFor   string                 `protobuf:"bytes,2,opt,name=schedule_for,json=scheduleFor,proto3" json:"schedule_for,omitempty"` // ISO8601
	ListIds       []string               `protobuf:"bytes,3,rep,name=list_ids,json=listIds,proto3" json:"list_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEmailRequest) Reset() {
	*x = ScheduleEmailRequest{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEmailRequest) ProtoMessage() {}

func (x *ScheduleEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEmailRequest.ProtoReflect.Descriptor instead.
func (*ScheduleEmailRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleEmailRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ScheduleEmailRequest) GetScheduleFor() string {
	if x != nil {
		return x.ScheduleFor
	}
	return ""
}

func (x *ScheduleEmailRequest) GetListIds() []string {
	if x != nil {
		return x.ListIds
	}
	return nil
}

type ScheduleEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEmailResponse) Reset() {
	*x = ScheduleEmailResponse{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEmailResponse) ProtoMessage() {}

func (x *ScheduleEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEmailResponse.ProtoReflect.Descriptor instead.
func (*ScheduleEmailResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleEmailResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelScheduledEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduledEmailRequest) Reset() {
	*x = CancelScheduledEmailRequest{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduledEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledEmailRequest) ProtoMessage() {}

func (x *CancelScheduledEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledEmailRequest.ProtoReflect.Descriptor instead.
func (*CancelScheduledEmailRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{2}
}

func (x *CancelScheduledEmailRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type CancelScheduledEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduledEmailResponse) Reset() {
	*x = CancelScheduledEmailResponse{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduledEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledEmailResponse) ProtoMessage() {}

func (x *CancelScheduledEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledEmailResponse.ProtoReflect.Descriptor instead.
func (*CancelScheduledEmailResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{3}
}

func (x *CancelScheduledEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelScheduledEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DispatchEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampaignId      string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	RecipientEmails []string               `protobuf:"bytes,2,rep,name=recipient_emails,json=recipientEmails,proto3" json:"recipient_emails,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchEmailRequest) Reset() {
	*x = DispatchEmailRequest{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchEmailRequest) ProtoMessage() {}

func (x *DispatchEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchEmailRequest.ProtoReflect.Descriptor instead.
func (*DispatchEmailRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchEmailRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DispatchEmailRequest) GetRecipientEmails() []string {
	if x != nil {
		return x.RecipientEmails
	}
	return nil
}

type DispatchEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchEmailResponse) Reset() {
	*x = DispatchEmailResponse{}
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchEmailResponse) ProtoMessage() {}

func (x *DispatchEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchEmailResponse.ProtoReflect.Descriptor instead.
func (*DispatchEmailResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP(), []int{5}
}

func (x *DispatchEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchEmailResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DispatchEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dispatcher_v1_email_scheduler_dispatcher_proto protoreflect.FileDescriptor

const file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDesc = "" +
	"\n" +
	".dispatcher/v1/email_scheduler_dispatcher.proto\x12\x0eemailscheduler\"u\n" +
	"\x14ScheduleEmailRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fschedule_for\x18\x02 \x01(\tR\vscheduleFor\x12\x19\n" +
	"\blist_ids\x18\x03 \x03(\tR\alistIds\"l\n" +
	"\x15ScheduleEmailResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\">\n" +
	"\x1bCancelScheduledEmailRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"R\n" +
	"\x1cCancelScheduledEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x14DispatchEmailRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12)\n" +
	"\x10recipient_emails\x18\x02 \x03(\tR\x0frecipientEmails\"r\n" +
	"\x15DispatchEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xdc\x02\n" +
	"\x18EmailSchedulerDispatcher\x12d\n" +
	"\x15ScheduleEmailCampaign\x12$.emailscheduler.ScheduleEmailRequest\x1a%.emailscheduler.ScheduleEmailResponse\x12q\n" +
	"\x14CancelScheduledEmail\x12+.emailscheduler.CancelScheduledEmailRequest\x1a,.emailscheduler.CancelScheduledEmailResponse\x12g\n" +
	"\x18DispatchEmailImmediately\x12$.emailscheduler.DispatchEmailRequest\x1a%.emailscheduler.DispatchEmailResponseB5Z3github.com/ehsanshah/empire-protos/emailschedulerpbb\x06proto3"

var (
	file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescOnce sync.Once
	file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescData []byte
)

func file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescGZIP() []byte {
	file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescOnce.Do(func() {
		file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDesc), len(file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDesc)))
	})
	return file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDescData
}

var file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dispatcher_v1_email_scheduler_dispatcher_proto_goTypes = []any{
	(*ScheduleEmailRequest)(nil),         // 0: emailscheduler.ScheduleEmailRequest
	(*ScheduleEmailResponse)(nil),        // 1: emailscheduler.ScheduleEmailResponse
	(*CancelScheduledEmailRequest)(nil),  // 2: emailscheduler.CancelScheduledEmailRequest
	(*CancelScheduledEmailResponse)(nil), // 3: emailscheduler.CancelScheduledEmailResponse
	(*DispatchEmailRequest)(nil),         // 4: emailscheduler.DispatchEmailRequest
	(*DispatchEmailResponse)(nil),        // 5: emailscheduler.DispatchEmailResponse
}
var file_dispatcher_v1_email_scheduler_dispatcher_proto_depIdxs = []int32{
	0, // 0: emailscheduler.EmailSchedulerDispatcher.ScheduleEmailCampaign:input_type -> emailscheduler.ScheduleEmailRequest
	2, // 1: emailscheduler.EmailSchedulerDispatcher.CancelScheduledEmail:input_type -> emailscheduler.CancelScheduledEmailRequest
	4, // 2: emailscheduler.EmailSchedulerDispatcher.DispatchEmailImmediately:input_type -> emailscheduler.DispatchEmailRequest
	1, // 3: emailscheduler.EmailSchedulerDispatcher.ScheduleEmailCampaign:output_type -> emailscheduler.ScheduleEmailResponse
	3, // 4: emailscheduler.EmailSchedulerDispatcher.CancelScheduledEmail:output_type -> emailscheduler.CancelScheduledEmailResponse
	5, // 5: emailscheduler.EmailSchedulerDispatcher.DispatchEmailImmediately:output_type -> emailscheduler.DispatchEmailResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatcher_v1_email_scheduler_dispatcher_proto_init() }
func file_dispatcher_v1_email_scheduler_dispatcher_proto_init() {
	if File_dispatcher_v1_email_scheduler_dispatcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDesc), len(file_dispatcher_v1_email_scheduler_dispatcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatcher_v1_email_scheduler_dispatcher_proto_goTypes,
		DependencyIndexes: file_dispatcher_v1_email_scheduler_dispatcher_proto_depIdxs,
		MessageInfos:      file_dispatcher_v1_email_scheduler_dispatcher_proto_msgTypes,
	}.Build()
	File_dispatcher_v1_email_scheduler_dispatcher_proto = out.File
	file_dispatcher_v1_email_scheduler_dispatcher_proto_goTypes = nil
	file_dispatcher_v1_email_scheduler_dispatcher_proto_depIdxs = nil
}
