// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: reports/v1/report_ad.proto

package reportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportAdService_GetAdPerformance_FullMethodName = "/report.v1.ReportAdService/GetAdPerformance"
)

// ReportAdServiceClient is the client API for ReportAdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// تعریف سرویس
type ReportAdServiceClient interface {
	// این همان متدی است که ایراد گرفته بودید
	GetAdPerformance(ctx context.Context, in *GetAdPerformanceRequest, opts ...grpc.CallOption) (*GetAdPerformanceResponse, error)
}

type reportAdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportAdServiceClient(cc grpc.ClientConnInterface) ReportAdServiceClient {
	return &reportAdServiceClient{cc}
}

func (c *reportAdServiceClient) GetAdPerformance(ctx context.Context, in *GetAdPerformanceRequest, opts ...grpc.CallOption) (*GetAdPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdPerformanceResponse)
	err := c.cc.Invoke(ctx, ReportAdService_GetAdPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportAdServiceServer is the server API for ReportAdService service.
// All implementations must embed UnimplementedReportAdServiceServer
// for forward compatibility.
//
// تعریف سرویس
type ReportAdServiceServer interface {
	// این همان متدی است که ایراد گرفته بودید
	GetAdPerformance(context.Context, *GetAdPerformanceRequest) (*GetAdPerformanceResponse, error)
	mustEmbedUnimplementedReportAdServiceServer()
}

// UnimplementedReportAdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportAdServiceServer struct{}

func (UnimplementedReportAdServiceServer) GetAdPerformance(context.Context, *GetAdPerformanceRequest) (*GetAdPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdPerformance not implemented")
}
func (UnimplementedReportAdServiceServer) mustEmbedUnimplementedReportAdServiceServer() {}
func (UnimplementedReportAdServiceServer) testEmbeddedByValue()                         {}

// UnsafeReportAdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportAdServiceServer will
// result in compilation errors.
type UnsafeReportAdServiceServer interface {
	mustEmbedUnimplementedReportAdServiceServer()
}

func RegisterReportAdServiceServer(s grpc.ServiceRegistrar, srv ReportAdServiceServer) {
	// If the following call panics, it indicates UnimplementedReportAdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportAdService_ServiceDesc, srv)
}

func _ReportAdService_GetAdPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportAdServiceServer).GetAdPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportAdService_GetAdPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportAdServiceServer).GetAdPerformance(ctx, req.(*GetAdPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportAdService_ServiceDesc is the grpc.ServiceDesc for ReportAdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportAdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.v1.ReportAdService",
	HandlerType: (*ReportAdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdPerformance",
			Handler:    _ReportAdService_GetAdPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reports/v1/report_ad.proto",
}
