// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: file/v1/files.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// پیام آپلود فایل
type UploadFileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BinaryContent    []byte                 `protobuf:"bytes,1,opt,name=binary_content,json=binaryContent,proto3" json:"binary_content,omitempty"`             // محتوای فایل به صورت باینری
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                    // نام فایل (با پسوند، مثلا "photo.png")
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                   // نوع محتوا (مثلا image/jpeg)
	ExpiresAfterDays int32                  `protobuf:"varint,4,opt,name=expires_after_days,json=expiresAfterDays,proto3" json:"expires_after_days,omitempty"` // تعداد روز اعتبار فایل (اختیاری)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_file_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetBinaryContent() []byte {
	if x != nil {
		return x.BinaryContent
	}
	return nil
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileRequest) GetExpiresAfterDays() int32 {
	if x != nil {
		return x.ExpiresAfterDays
	}
	return 0
}

// پیام ویرایش فایل
type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // نام فایل (جهت جستجو و شناسایی)
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`             // نام جدید (اختیاری)
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // نوع جدید محتوا (اختیاری)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_file_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *UpdateFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// پیام حذف فایل
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // نام فایل برای حذف (با پسوند)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_file_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// پیام لیست‌گیری فایل‌ها
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // تعداد فایل در هر صفحه (اختیاری)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // جابجایی برای صفحه‌بندی (اختیاری)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_file_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// پاسخ آپلود فایل
type UploadFileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileName       string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                   // نام فایل آپلودشده
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                          // اندازه فایل (بر حسب بایت)
	DateAdded      string                 `protobuf:"bytes,3,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`                // زمان آپلود فایل
	ExpirationDate string                 `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"` // تاریخ حذف اتوماتیک فایل (اختیاری)
	ContentType    string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`          // نوع محتوا (مثلا image/jpeg)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_file_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileResponse) GetDateAdded() string {
	if x != nil {
		return x.DateAdded
	}
	return ""
}

func (x *UploadFileResponse) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *UploadFileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// پاسخ ویرایش فایل
type UpdateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // نام جدید یا فعلی فایل
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // پیام نتیجه ویرایش (مثلاً موفقیت/خطا)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileResponse) Reset() {
	*x = UpdateFileResponse{}
	mi := &file_file_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileResponse) ProtoMessage() {}

func (x *UpdateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UpdateFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// پاسخ حذف فایل
type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // نام فایل حذف شده
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // پیام وضعیت حذف (مثلا "حذف موفق" یا "یافت نشد")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_file_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// مدل اطلاعات هر فایل
type FileInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileName       string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                   // نام فایل
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                          // اندازه فایل (بر حسب بایت)
	DateAdded      string                 `protobuf:"bytes,3,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`                // تاریخ و ساعت آپلود
	ExpirationDate string                 `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"` // زمان حذف فایل (در صورت فعال بودن حذف خودکار)
	ContentType    string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`          // نوع فایل
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_file_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetDateAdded() string {
	if x != nil {
		return x.DateAdded
	}
	return ""
}

func (x *FileInfo) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// پاسخ لیست فایل‌ها
type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FileInfo            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`    // لیست اطلاعات فایل‌های این صفحه
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`   // تعداد کل فایل‌ها
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // اندازه صفحه
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"` // جابجایی صفحه‌بندی
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_file_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilesResponse) GetItems() []*FileInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFilesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_file_v1_files_proto protoreflect.FileDescriptor

const file_file_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x13file/v1/files.proto\x12\x04file\"\x9f\x01\n" +
	"\x11UploadFileRequest\x12%\n" +
	"\x0ebinary_content\x18\x01 \x01(\fR\rbinaryContent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12,\n" +
	"\x12expires_after_days\x18\x04 \x01(\x05R\x10expiresAfterDays\"e\n" +
	"\x11UpdateFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x10ListFilesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xb0\x01\n" +
	"\x12UploadFileResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"date_added\x18\x03 \x01(\tR\tdateAdded\x12'\n" +
	"\x0fexpiration_date\x18\x04 \x01(\tR\x0eexpirationDate\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"K\n" +
	"\x12UpdateFileResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x12DeleteFileResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\bFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"date_added\x18\x03 \x01(\tR\tdateAdded\x12'\n" +
	"\x0fexpiration_date\x18\x04 \x01(\tR\x0eexpirationDate\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"}\n" +
	"\x11ListFilesResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.file.FileInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset2\x8e\x02\n" +
	"\vFileService\x12?\n" +
	"\n" +
	"UploadFile\x12\x17.file.UploadFileRequest\x1a\x18.file.UploadFileResponse\x12?\n" +
	"\n" +
	"UpdateFile\x12\x17.file.UpdateFileRequest\x1a\x18.file.UpdateFileResponse\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.file.DeleteFileRequest\x1a\x18.file.DeleteFileResponse\x12<\n" +
	"\tListFiles\x12\x16.file.ListFilesRequest\x1a\x17.file.ListFilesResponseB+Z)github.com/ehsanshah/empire-protos/filepbb\x06proto3"

var (
	file_file_v1_files_proto_rawDescOnce sync.Once
	file_file_v1_files_proto_rawDescData []byte
)

func file_file_v1_files_proto_rawDescGZIP() []byte {
	file_file_v1_files_proto_rawDescOnce.Do(func() {
		file_file_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_files_proto_rawDesc), len(file_file_v1_files_proto_rawDesc)))
	})
	return file_file_v1_files_proto_rawDescData
}

var file_file_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_file_v1_files_proto_goTypes = []any{
	(*UploadFileRequest)(nil),  // 0: file.UploadFileRequest
	(*UpdateFileRequest)(nil),  // 1: file.UpdateFileRequest
	(*DeleteFileRequest)(nil),  // 2: file.DeleteFileRequest
	(*ListFilesRequest)(nil),   // 3: file.ListFilesRequest
	(*UploadFileResponse)(nil), // 4: file.UploadFileResponse
	(*UpdateFileResponse)(nil), // 5: file.UpdateFileResponse
	(*DeleteFileResponse)(nil), // 6: file.DeleteFileResponse
	(*FileInfo)(nil),           // 7: file.FileInfo
	(*ListFilesResponse)(nil),  // 8: file.ListFilesResponse
}
var file_file_v1_files_proto_depIdxs = []int32{
	7, // 0: file.ListFilesResponse.items:type_name -> file.FileInfo
	0, // 1: file.FileService.UploadFile:input_type -> file.UploadFileRequest
	1, // 2: file.FileService.UpdateFile:input_type -> file.UpdateFileRequest
	2, // 3: file.FileService.DeleteFile:input_type -> file.DeleteFileRequest
	3, // 4: file.FileService.ListFiles:input_type -> file.ListFilesRequest
	4, // 5: file.FileService.UploadFile:output_type -> file.UploadFileResponse
	5, // 6: file.FileService.UpdateFile:output_type -> file.UpdateFileResponse
	6, // 7: file.FileService.DeleteFile:output_type -> file.DeleteFileResponse
	8, // 8: file.FileService.ListFiles:output_type -> file.ListFilesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_v1_files_proto_init() }
func file_file_v1_files_proto_init() {
	if File_file_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_files_proto_rawDesc), len(file_file_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_files_proto_goTypes,
		DependencyIndexes: file_file_v1_files_proto_depIdxs,
		MessageInfos:      file_file_v1_files_proto_msgTypes,
	}.Build()
	File_file_v1_files_proto = out.File
	file_file_v1_files_proto_goTypes = nil
	file_file_v1_files_proto_depIdxs = nil
}
