// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: audience/v1/audience.proto

package audiencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAudienceManagementservices_CreateGroup_FullMethodName           = "/audience.v1.IAudienceManagementservices/CreateGroup"
	IAudienceManagementservices_UpdateGroup_FullMethodName           = "/audience.v1.IAudienceManagementservices/UpdateGroup"
	IAudienceManagementservices_DeleteGroup_FullMethodName           = "/audience.v1.IAudienceManagementservices/DeleteGroup"
	IAudienceManagementservices_ListGroups_FullMethodName            = "/audience.v1.IAudienceManagementservices/ListGroups"
	IAudienceManagementservices_GetGroup_FullMethodName              = "/audience.v1.IAudienceManagementservices/GetGroup"
	IAudienceManagementservices_CreateList_FullMethodName            = "/audience.v1.IAudienceManagementservices/CreateList"
	IAudienceManagementservices_UpdateList_FullMethodName            = "/audience.v1.IAudienceManagementservices/UpdateList"
	IAudienceManagementservices_DeleteList_FullMethodName            = "/audience.v1.IAudienceManagementservices/DeleteList"
	IAudienceManagementservices_ListLists_FullMethodName             = "/audience.v1.IAudienceManagementservices/ListLists"
	IAudienceManagementservices_GetList_FullMethodName               = "/audience.v1.IAudienceManagementservices/GetList"
	IAudienceManagementservices_AddMembersToList_FullMethodName      = "/audience.v1.IAudienceManagementservices/AddMembersToList"
	IAudienceManagementservices_RemoveMembersFromList_FullMethodName = "/audience.v1.IAudienceManagementservices/RemoveMembersFromList"
	IAudienceManagementservices_ListMembers_FullMethodName           = "/audience.v1.IAudienceManagementservices/ListMembers"
	IAudienceManagementservices_GetMember_FullMethodName             = "/audience.v1.IAudienceManagementservices/GetMember"
	IAudienceManagementservices_BulkUploadMembers_FullMethodName     = "/audience.v1.IAudienceManagementservices/BulkUploadMembers"
)

// IAudienceManagementservicesClient is the client API for IAudienceManagementservices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// سرویس مدیریت هوشمند مخاطبین (Audience Management Services)
// این سرویس لایه گروه‌بندی و مدیریت لیست‌ها را با قابلیت تنظیمات JSON فراهم می‌کند.
type IAudienceManagementservicesClient interface {
	// --- مدیریت گروه‌ها (Virtual Grouping) ---
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error)
	// --- مدیریت لیست‌ها (Mailing Lists) ---
	CreateList(ctx context.Context, in *CreateListRequest, opts ...grpc.CallOption) (*ListDetail, error)
	UpdateList(ctx context.Context, in *UpdateListRequest, opts ...grpc.CallOption) (*ListDetail, error)
	DeleteList(ctx context.Context, in *DeleteListRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ListLists(ctx context.Context, in *ListListsRequest, opts ...grpc.CallOption) (*ListListsResponse, error)
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*ListDetail, error)
	// --- مدیریت اعضا (Member Operations) ---
	AddMembersToList(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	RemoveMembersFromList(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*MemberDetail, error)
	// عملیات حجیم (Bulk Operations)
	BulkUploadMembers(ctx context.Context, in *BulkUploadRequest, opts ...grpc.CallOption) (*BulkUploadResponse, error)
}

type iAudienceManagementservicesClient struct {
	cc grpc.ClientConnInterface
}

func NewIAudienceManagementservicesClient(cc grpc.ClientConnInterface) IAudienceManagementservicesClient {
	return &iAudienceManagementservicesClient{cc}
}

func (c *iAudienceManagementservicesClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) CreateList(ctx context.Context, in *CreateListRequest, opts ...grpc.CallOption) (*ListDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_CreateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) UpdateList(ctx context.Context, in *UpdateListRequest, opts ...grpc.CallOption) (*ListDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_UpdateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) DeleteList(ctx context.Context, in *DeleteListRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_DeleteList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) ListLists(ctx context.Context, in *ListListsRequest, opts ...grpc.CallOption) (*ListListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListListsResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_ListLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*ListDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) AddMembersToList(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_AddMembersToList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) RemoveMembersFromList(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_RemoveMembersFromList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*MemberDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberDetail)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAudienceManagementservicesClient) BulkUploadMembers(ctx context.Context, in *BulkUploadRequest, opts ...grpc.CallOption) (*BulkUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUploadResponse)
	err := c.cc.Invoke(ctx, IAudienceManagementservices_BulkUploadMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAudienceManagementservicesServer is the server API for IAudienceManagementservices service.
// All implementations must embed UnimplementedIAudienceManagementservicesServer
// for forward compatibility.
//
// سرویس مدیریت هوشمند مخاطبین (Audience Management Services)
// این سرویس لایه گروه‌بندی و مدیریت لیست‌ها را با قابلیت تنظیمات JSON فراهم می‌کند.
type IAudienceManagementservicesServer interface {
	// --- مدیریت گروه‌ها (Virtual Grouping) ---
	CreateGroup(context.Context, *CreateGroupRequest) (*GroupDetail, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupDetail, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*ActionResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GroupDetail, error)
	// --- مدیریت لیست‌ها (Mailing Lists) ---
	CreateList(context.Context, *CreateListRequest) (*ListDetail, error)
	UpdateList(context.Context, *UpdateListRequest) (*ListDetail, error)
	DeleteList(context.Context, *DeleteListRequest) (*ActionResponse, error)
	ListLists(context.Context, *ListListsRequest) (*ListListsResponse, error)
	GetList(context.Context, *GetListRequest) (*ListDetail, error)
	// --- مدیریت اعضا (Member Operations) ---
	AddMembersToList(context.Context, *AddMembersRequest) (*ActionResponse, error)
	RemoveMembersFromList(context.Context, *RemoveMembersRequest) (*ActionResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	GetMember(context.Context, *GetMemberRequest) (*MemberDetail, error)
	// عملیات حجیم (Bulk Operations)
	BulkUploadMembers(context.Context, *BulkUploadRequest) (*BulkUploadResponse, error)
	mustEmbedUnimplementedIAudienceManagementservicesServer()
}

// UnimplementedIAudienceManagementservicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAudienceManagementservicesServer struct{}

func (UnimplementedIAudienceManagementservicesServer) CreateGroup(context.Context, *CreateGroupRequest) (*GroupDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) GetGroup(context.Context, *GetGroupRequest) (*GroupDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) CreateList(context.Context, *CreateListRequest) (*ListDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) UpdateList(context.Context, *UpdateListRequest) (*ListDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) DeleteList(context.Context, *DeleteListRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) ListLists(context.Context, *ListListsRequest) (*ListListsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLists not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) GetList(context.Context, *GetListRequest) (*ListDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) AddMembersToList(context.Context, *AddMembersRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMembersToList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) RemoveMembersFromList(context.Context, *RemoveMembersRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMembersFromList not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) GetMember(context.Context, *GetMemberRequest) (*MemberDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) BulkUploadMembers(context.Context, *BulkUploadRequest) (*BulkUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUploadMembers not implemented")
}
func (UnimplementedIAudienceManagementservicesServer) mustEmbedUnimplementedIAudienceManagementservicesServer() {
}
func (UnimplementedIAudienceManagementservicesServer) testEmbeddedByValue() {}

// UnsafeIAudienceManagementservicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAudienceManagementservicesServer will
// result in compilation errors.
type UnsafeIAudienceManagementservicesServer interface {
	mustEmbedUnimplementedIAudienceManagementservicesServer()
}

func RegisterIAudienceManagementservicesServer(s grpc.ServiceRegistrar, srv IAudienceManagementservicesServer) {
	// If the following call panics, it indicates UnimplementedIAudienceManagementservicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAudienceManagementservices_ServiceDesc, srv)
}

func _IAudienceManagementservices_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_CreateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).CreateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_CreateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).CreateList(ctx, req.(*CreateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_UpdateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).UpdateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_UpdateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).UpdateList(ctx, req.(*UpdateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_DeleteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).DeleteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_DeleteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).DeleteList(ctx, req.(*DeleteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_ListLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).ListLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_ListLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).ListLists(ctx, req.(*ListListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_AddMembersToList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).AddMembersToList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_AddMembersToList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).AddMembersToList(ctx, req.(*AddMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_RemoveMembersFromList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).RemoveMembersFromList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_RemoveMembersFromList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).RemoveMembersFromList(ctx, req.(*RemoveMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAudienceManagementservices_BulkUploadMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAudienceManagementservicesServer).BulkUploadMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAudienceManagementservices_BulkUploadMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAudienceManagementservicesServer).BulkUploadMembers(ctx, req.(*BulkUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAudienceManagementservices_ServiceDesc is the grpc.ServiceDesc for IAudienceManagementservices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAudienceManagementservices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audience.v1.IAudienceManagementservices",
	HandlerType: (*IAudienceManagementservicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _IAudienceManagementservices_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _IAudienceManagementservices_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _IAudienceManagementservices_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _IAudienceManagementservices_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _IAudienceManagementservices_GetGroup_Handler,
		},
		{
			MethodName: "CreateList",
			Handler:    _IAudienceManagementservices_CreateList_Handler,
		},
		{
			MethodName: "UpdateList",
			Handler:    _IAudienceManagementservices_UpdateList_Handler,
		},
		{
			MethodName: "DeleteList",
			Handler:    _IAudienceManagementservices_DeleteList_Handler,
		},
		{
			MethodName: "ListLists",
			Handler:    _IAudienceManagementservices_ListLists_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _IAudienceManagementservices_GetList_Handler,
		},
		{
			MethodName: "AddMembersToList",
			Handler:    _IAudienceManagementservices_AddMembersToList_Handler,
		},
		{
			MethodName: "RemoveMembersFromList",
			Handler:    _IAudienceManagementservices_RemoveMembersFromList_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _IAudienceManagementservices_ListMembers_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _IAudienceManagementservices_GetMember_Handler,
		},
		{
			MethodName: "BulkUploadMembers",
			Handler:    _IAudienceManagementservices_BulkUploadMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audience/v1/audience.proto",
}
