// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: audience/v1/audience.proto

package audiencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AllowUnsubscribe bool                   `protobuf:"varint,4,opt,name=allow_unsubscribe,json=allowUnsubscribe,proto3" json:"allow_unsubscribe,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetAllowUnsubscribe() bool {
	if x != nil {
		return x.AllowUnsubscribe
	}
	return false
}

type UpdateGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GroupId          string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AllowUnsubscribe bool                   `protobuf:"varint,5,opt,name=allow_unsubscribe,json=allowUnsubscribe,proto3" json:"allow_unsubscribe,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateGroupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetAllowUnsubscribe() bool {
	if x != nil {
		return x.AllowUnsubscribe
	}
	return false
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteGroupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type GroupDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ListCount        int32                  `protobuf:"varint,4,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	AllowUnsubscribe bool                   `protobuf:"varint,5,opt,name=allow_unsubscribe,json=allowUnsubscribe,proto3" json:"allow_unsubscribe,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupDetail) Reset() {
	*x = GroupDetail{}
	mi := &file_audience_v1_audience_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetail) ProtoMessage() {}

func (x *GroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetail.ProtoReflect.Descriptor instead.
func (*GroupDetail) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{5}
}

func (x *GroupDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupDetail) GetListCount() int32 {
	if x != nil {
		return x.ListCount
	}
	return 0
}

func (x *GroupDetail) GetAllowUnsubscribe() bool {
	if x != nil {
		return x.AllowUnsubscribe
	}
	return false
}

func (x *GroupDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // اختیاری
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Settings      string                 `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"` // فیلد درخواستی جهت ذخیره تنظیمات به صورت JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListRequest) Reset() {
	*x = CreateListRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListRequest) ProtoMessage() {}

func (x *CreateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListRequest.ProtoReflect.Descriptor instead.
func (*CreateListRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{6}
}

func (x *CreateListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateListRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateListRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type UpdateListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Settings      string                 `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"` // فیلد جدید جهت بروزرسانی JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListRequest) Reset() {
	*x = UpdateListRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListRequest) ProtoMessage() {}

func (x *UpdateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListRequest.ProtoReflect.Descriptor instead.
func (*UpdateListRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *UpdateListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateListRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type DeleteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListRequest) Reset() {
	*x = DeleteListRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListRequest) ProtoMessage() {}

func (x *DeleteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListRequest.ProtoReflect.Descriptor instead.
func (*DeleteListRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{9}
}

func (x *GetListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type ListListsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // فیلتر لیست‌ها بر اساس گروه
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListsRequest) Reset() {
	*x = ListListsRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListsRequest) ProtoMessage() {}

func (x *ListListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListsRequest.ProtoReflect.Descriptor instead.
func (*ListListsRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{10}
}

func (x *ListListsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListListsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListListsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListListsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type ListDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	MemberCount   int64                  `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	Settings      string                 `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"` // بازگرداندن تنظیمات JSON به کلاینت
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDetail) Reset() {
	*x = ListDetail{}
	mi := &file_audience_v1_audience_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetail) ProtoMessage() {}

func (x *ListDetail) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetail.ProtoReflect.Descriptor instead.
func (*ListDetail) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{11}
}

func (x *ListDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListDetail) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListDetail) GetMemberCount() int64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *ListDetail) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *ListDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // برای واکشی اعضای کل یک گروه
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // برای Pagination با کارایی بالا در ScyllaDB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListMembersRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *ListMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{13}
}

func (x *GetMemberRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Members       []*MemberInfo          `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{14}
}

func (x *AddMembersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddMembersRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *AddMembersRequest) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type RemoveMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Emails        []string               `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMembersRequest) Reset() {
	*x = RemoveMembersRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersRequest) ProtoMessage() {}

func (x *RemoveMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveMembersRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveMembersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RemoveMembersRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *RemoveMembersRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_audience_v1_audience_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{16}
}

func (x *MemberInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MemberInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MemberInfo) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type MemberDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDetail) Reset() {
	*x = MemberDetail{}
	mi := &file_audience_v1_audience_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDetail) ProtoMessage() {}

func (x *MemberDetail) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDetail.ProtoReflect.Descriptor instead.
func (*MemberDetail) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{17}
}

func (x *MemberDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberDetail) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MemberDetail) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MemberDetail) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *MemberDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MemberDetail) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type BulkUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ListId        string                 `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // "csv" یا "json"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUploadRequest) Reset() {
	*x = BulkUploadRequest{}
	mi := &file_audience_v1_audience_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUploadRequest) ProtoMessage() {}

func (x *BulkUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUploadRequest.ProtoReflect.Descriptor instead.
func (*BulkUploadRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{18}
}

func (x *BulkUploadRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BulkUploadRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *BulkUploadRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *BulkUploadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type BulkUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TotalRecords  int32                  `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUploadResponse) Reset() {
	*x = BulkUploadResponse{}
	mi := &file_audience_v1_audience_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUploadResponse) ProtoMessage() {}

func (x *BulkUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUploadResponse.ProtoReflect.Descriptor instead.
func (*BulkUploadResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{19}
}

func (x *BulkUploadResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BulkUploadResponse) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_audience_v1_audience_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{20}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupDetail         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_audience_v1_audience_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{21}
}

func (x *ListGroupsResponse) GetGroups() []*GroupDetail {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         []*ListDetail          `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListsResponse) Reset() {
	*x = ListListsResponse{}
	mi := &file_audience_v1_audience_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListsResponse) ProtoMessage() {}

func (x *ListListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListsResponse.ProtoReflect.Descriptor instead.
func (*ListListsResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{22}
}

func (x *ListListsResponse) GetLists() []*ListDetail {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *ListListsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberDetail        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_audience_v1_audience_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_audience_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_audience_proto_rawDescGZIP(), []int{23}
}

func (x *ListMembersResponse) GetMembers() []*MemberDetail {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_audience_v1_audience_proto protoreflect.FileDescriptor

const file_audience_v1_audience_proto_rawDesc = "" +
	"\n" +
	"\x1aaudience/v1/audience.proto\x12\vaudience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\x12CreateGroupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11allow_unsubscribe\x18\x04 \x01(\bR\x10allowUnsubscribe\"\xb1\x01\n" +
	"\x12UpdateGroupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12+\n" +
	"\x11allow_unsubscribe\x18\x05 \x01(\bR\x10allowUnsubscribe\"N\n" +
	"\x12DeleteGroupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"K\n" +
	"\x0fGetGroupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\\\n" +
	"\x11ListGroupsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x05R\x04skip\"\xda\x01\n" +
	"\vGroupDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"list_count\x18\x04 \x01(\x05R\tlistCount\x12+\n" +
	"\x11allow_unsubscribe\x18\x05 \x01(\bR\x10allowUnsubscribe\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x97\x01\n" +
	"\x11CreateListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\bsettings\x18\x05 \x01(\tR\bsettings\"\x96\x01\n" +
	"\x11UpdateListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bsettings\x18\x05 \x01(\tR\bsettings\"K\n" +
	"\x11DeleteListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\"H\n" +
	"\x0eGetListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\"v\n" +
	"\x10ListListsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x05R\x04skip\"\xdf\x01\n" +
	"\n" +
	"ListDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\fmember_count\x18\x05 \x01(\x03R\vmemberCount\x12\x1a\n" +
	"\bsettings\x18\x06 \x01(\tR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9c\x01\n" +
	"\x12ListMembersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"G\n" +
	"\x10GetMemberRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"~\n" +
	"\x11AddMembersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.audience.v1.MemberInfoR\amembers\"f\n" +
	"\x14RemoveMembersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12\x16\n" +
	"\x06emails\x18\x03 \x03(\tR\x06emails\"\xe6\x01\n" +
	"\n" +
	"MemberInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12G\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2'.audience.v1.MemberInfo.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x02\n" +
	"\fMemberDetail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12I\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2).audience.v1.MemberDetail.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x11BulkUploadRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\tR\x06listId\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"P\n" +
	"\x12BulkUploadResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rtotal_records\x18\x02 \x01(\x05R\ftotalRecords\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\x12ListGroupsResponse\x120\n" +
	"\x06groups\x18\x01 \x03(\v2\x18.audience.v1.GroupDetailR\x06groups\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"X\n" +
	"\x11ListListsResponse\x12-\n" +
	"\x05lists\x18\x01 \x03(\v2\x17.audience.v1.ListDetailR\x05lists\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x88\x01\n" +
	"\x13ListMembersResponse\x123\n" +
	"\amembers\x18\x01 \x03(\v2\x19.audience.v1.MemberDetailR\amembers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2\x90\t\n" +
	"\x1bIAudienceManagementservices\x12H\n" +
	"\vCreateGroup\x12\x1f.audience.v1.CreateGroupRequest\x1a\x18.audience.v1.GroupDetail\x12H\n" +
	"\vUpdateGroup\x12\x1f.audience.v1.UpdateGroupRequest\x1a\x18.audience.v1.GroupDetail\x12K\n" +
	"\vDeleteGroup\x12\x1f.audience.v1.DeleteGroupRequest\x1a\x1b.audience.v1.ActionResponse\x12M\n" +
	"\n" +
	"ListGroups\x12\x1e.audience.v1.ListGroupsRequest\x1a\x1f.audience.v1.ListGroupsResponse\x12B\n" +
	"\bGetGroup\x12\x1c.audience.v1.GetGroupRequest\x1a\x18.audience.v1.GroupDetail\x12E\n" +
	"\n" +
	"CreateList\x12\x1e.audience.v1.CreateListRequest\x1a\x17.audience.v1.ListDetail\x12E\n" +
	"\n" +
	"UpdateList\x12\x1e.audience.v1.UpdateListRequest\x1a\x17.audience.v1.ListDetail\x12I\n" +
	"\n" +
	"DeleteList\x12\x1e.audience.v1.DeleteListRequest\x1a\x1b.audience.v1.ActionResponse\x12J\n" +
	"\tListLists\x12\x1d.audience.v1.ListListsRequest\x1a\x1e.audience.v1.ListListsResponse\x12?\n" +
	"\aGetList\x12\x1b.audience.v1.GetListRequest\x1a\x17.audience.v1.ListDetail\x12O\n" +
	"\x10AddMembersToList\x12\x1e.audience.v1.AddMembersRequest\x1a\x1b.audience.v1.ActionResponse\x12W\n" +
	"\x15RemoveMembersFromList\x12!.audience.v1.RemoveMembersRequest\x1a\x1b.audience.v1.ActionResponse\x12P\n" +
	"\vListMembers\x12\x1f.audience.v1.ListMembersRequest\x1a .audience.v1.ListMembersResponse\x12E\n" +
	"\tGetMember\x12\x1d.audience.v1.GetMemberRequest\x1a\x19.audience.v1.MemberDetail\x12T\n" +
	"\x11BulkUploadMembers\x12\x1e.audience.v1.BulkUploadRequest\x1a\x1f.audience.v1.BulkUploadResponseBFZDgithub.com/ehsanshah/empire-protos/src/pkg/pb/audience/v1;audiencev1b\x06proto3"

var (
	file_audience_v1_audience_proto_rawDescOnce sync.Once
	file_audience_v1_audience_proto_rawDescData []byte
)

func file_audience_v1_audience_proto_rawDescGZIP() []byte {
	file_audience_v1_audience_proto_rawDescOnce.Do(func() {
		file_audience_v1_audience_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audience_v1_audience_proto_rawDesc), len(file_audience_v1_audience_proto_rawDesc)))
	})
	return file_audience_v1_audience_proto_rawDescData
}

var file_audience_v1_audience_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_audience_v1_audience_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),    // 0: audience.v1.CreateGroupRequest
	(*UpdateGroupRequest)(nil),    // 1: audience.v1.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),    // 2: audience.v1.DeleteGroupRequest
	(*GetGroupRequest)(nil),       // 3: audience.v1.GetGroupRequest
	(*ListGroupsRequest)(nil),     // 4: audience.v1.ListGroupsRequest
	(*GroupDetail)(nil),           // 5: audience.v1.GroupDetail
	(*CreateListRequest)(nil),     // 6: audience.v1.CreateListRequest
	(*UpdateListRequest)(nil),     // 7: audience.v1.UpdateListRequest
	(*DeleteListRequest)(nil),     // 8: audience.v1.DeleteListRequest
	(*GetListRequest)(nil),        // 9: audience.v1.GetListRequest
	(*ListListsRequest)(nil),      // 10: audience.v1.ListListsRequest
	(*ListDetail)(nil),            // 11: audience.v1.ListDetail
	(*ListMembersRequest)(nil),    // 12: audience.v1.ListMembersRequest
	(*GetMemberRequest)(nil),      // 13: audience.v1.GetMemberRequest
	(*AddMembersRequest)(nil),     // 14: audience.v1.AddMembersRequest
	(*RemoveMembersRequest)(nil),  // 15: audience.v1.RemoveMembersRequest
	(*MemberInfo)(nil),            // 16: audience.v1.MemberInfo
	(*MemberDetail)(nil),          // 17: audience.v1.MemberDetail
	(*BulkUploadRequest)(nil),     // 18: audience.v1.BulkUploadRequest
	(*BulkUploadResponse)(nil),    // 19: audience.v1.BulkUploadResponse
	(*ActionResponse)(nil),        // 20: audience.v1.ActionResponse
	(*ListGroupsResponse)(nil),    // 21: audience.v1.ListGroupsResponse
	(*ListListsResponse)(nil),     // 22: audience.v1.ListListsResponse
	(*ListMembersResponse)(nil),   // 23: audience.v1.ListMembersResponse
	nil,                           // 24: audience.v1.MemberInfo.AttributesEntry
	nil,                           // 25: audience.v1.MemberDetail.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_audience_v1_audience_proto_depIdxs = []int32{
	26, // 0: audience.v1.GroupDetail.created_at:type_name -> google.protobuf.Timestamp
	26, // 1: audience.v1.ListDetail.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: audience.v1.AddMembersRequest.members:type_name -> audience.v1.MemberInfo
	24, // 3: audience.v1.MemberInfo.attributes:type_name -> audience.v1.MemberInfo.AttributesEntry
	25, // 4: audience.v1.MemberDetail.attributes:type_name -> audience.v1.MemberDetail.AttributesEntry
	26, // 5: audience.v1.MemberDetail.joined_at:type_name -> google.protobuf.Timestamp
	5,  // 6: audience.v1.ListGroupsResponse.groups:type_name -> audience.v1.GroupDetail
	11, // 7: audience.v1.ListListsResponse.lists:type_name -> audience.v1.ListDetail
	17, // 8: audience.v1.ListMembersResponse.members:type_name -> audience.v1.MemberDetail
	0,  // 9: audience.v1.IAudienceManagementservices.CreateGroup:input_type -> audience.v1.CreateGroupRequest
	1,  // 10: audience.v1.IAudienceManagementservices.UpdateGroup:input_type -> audience.v1.UpdateGroupRequest
	2,  // 11: audience.v1.IAudienceManagementservices.DeleteGroup:input_type -> audience.v1.DeleteGroupRequest
	4,  // 12: audience.v1.IAudienceManagementservices.ListGroups:input_type -> audience.v1.ListGroupsRequest
	3,  // 13: audience.v1.IAudienceManagementservices.GetGroup:input_type -> audience.v1.GetGroupRequest
	6,  // 14: audience.v1.IAudienceManagementservices.CreateList:input_type -> audience.v1.CreateListRequest
	7,  // 15: audience.v1.IAudienceManagementservices.UpdateList:input_type -> audience.v1.UpdateListRequest
	8,  // 16: audience.v1.IAudienceManagementservices.DeleteList:input_type -> audience.v1.DeleteListRequest
	10, // 17: audience.v1.IAudienceManagementservices.ListLists:input_type -> audience.v1.ListListsRequest
	9,  // 18: audience.v1.IAudienceManagementservices.GetList:input_type -> audience.v1.GetListRequest
	14, // 19: audience.v1.IAudienceManagementservices.AddMembersToList:input_type -> audience.v1.AddMembersRequest
	15, // 20: audience.v1.IAudienceManagementservices.RemoveMembersFromList:input_type -> audience.v1.RemoveMembersRequest
	12, // 21: audience.v1.IAudienceManagementservices.ListMembers:input_type -> audience.v1.ListMembersRequest
	13, // 22: audience.v1.IAudienceManagementservices.GetMember:input_type -> audience.v1.GetMemberRequest
	18, // 23: audience.v1.IAudienceManagementservices.BulkUploadMembers:input_type -> audience.v1.BulkUploadRequest
	5,  // 24: audience.v1.IAudienceManagementservices.CreateGroup:output_type -> audience.v1.GroupDetail
	5,  // 25: audience.v1.IAudienceManagementservices.UpdateGroup:output_type -> audience.v1.GroupDetail
	20, // 26: audience.v1.IAudienceManagementservices.DeleteGroup:output_type -> audience.v1.ActionResponse
	21, // 27: audience.v1.IAudienceManagementservices.ListGroups:output_type -> audience.v1.ListGroupsResponse
	5,  // 28: audience.v1.IAudienceManagementservices.GetGroup:output_type -> audience.v1.GroupDetail
	11, // 29: audience.v1.IAudienceManagementservices.CreateList:output_type -> audience.v1.ListDetail
	11, // 30: audience.v1.IAudienceManagementservices.UpdateList:output_type -> audience.v1.ListDetail
	20, // 31: audience.v1.IAudienceManagementservices.DeleteList:output_type -> audience.v1.ActionResponse
	22, // 32: audience.v1.IAudienceManagementservices.ListLists:output_type -> audience.v1.ListListsResponse
	11, // 33: audience.v1.IAudienceManagementservices.GetList:output_type -> audience.v1.ListDetail
	20, // 34: audience.v1.IAudienceManagementservices.AddMembersToList:output_type -> audience.v1.ActionResponse
	20, // 35: audience.v1.IAudienceManagementservices.RemoveMembersFromList:output_type -> audience.v1.ActionResponse
	23, // 36: audience.v1.IAudienceManagementservices.ListMembers:output_type -> audience.v1.ListMembersResponse
	17, // 37: audience.v1.IAudienceManagementservices.GetMember:output_type -> audience.v1.MemberDetail
	19, // 38: audience.v1.IAudienceManagementservices.BulkUploadMembers:output_type -> audience.v1.BulkUploadResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_audience_v1_audience_proto_init() }
func file_audience_v1_audience_proto_init() {
	if File_audience_v1_audience_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audience_v1_audience_proto_rawDesc), len(file_audience_v1_audience_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audience_v1_audience_proto_goTypes,
		DependencyIndexes: file_audience_v1_audience_proto_depIdxs,
		MessageInfos:      file_audience_v1_audience_proto_msgTypes,
	}.Build()
	File_audience_v1_audience_proto = out.File
	file_audience_v1_audience_proto_goTypes = nil
	file_audience_v1_audience_proto_depIdxs = nil
}
