// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: audience/v1/forms.proto

package audiencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ساخت فرم
type CreateFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // نام فرم
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // popup, embedded, promotion
	Custom        *structpb.Struct       `protobuf:"bytes,3,opt,name=custom,proto3" json:"custom,omitempty"` // تنظیمات سفارشی دلخواه
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormRequest) Reset() {
	*x = CreateFormRequest{}
	mi := &file_audience_v1_forms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormRequest) ProtoMessage() {}

func (x *CreateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormRequest.ProtoReflect.Descriptor instead.
func (*CreateFormRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFormRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFormRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFormRequest) GetCustom() *structpb.Struct {
	if x != nil {
		return x.Custom
	}
	return nil
}

// به‌روزرسانی فرم
type UpdateFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Custom        *structpb.Struct       `protobuf:"bytes,3,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormRequest) Reset() {
	*x = UpdateFormRequest{}
	mi := &file_audience_v1_forms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormRequest) ProtoMessage() {}

func (x *UpdateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *UpdateFormRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFormRequest) GetCustom() *structpb.Struct {
	if x != nil {
		return x.Custom
	}
	return nil
}

// لیست‌گیری
type ListFormsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsRequest) Reset() {
	*x = ListFormsRequest{}
	mi := &file_audience_v1_forms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsRequest) ProtoMessage() {}

func (x *ListFormsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsRequest.ProtoReflect.Descriptor instead.
func (*ListFormsRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{2}
}

func (x *ListFormsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListFormsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListFormsRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListFormsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFormsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFormsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListFormsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// حذف
type DeleteFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormRequest) Reset() {
	*x = DeleteFormRequest{}
	mi := &file_audience_v1_forms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormRequest) ProtoMessage() {}

func (x *DeleteFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

// پاسخ ایجاد/ویرایش فرم
type FormResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FormId             string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Slug               string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ConversionsCount   int32                  `protobuf:"varint,6,opt,name=conversions_count,json=conversionsCount,proto3" json:"conversions_count,omitempty"`
	OpensCount         int32                  `protobuf:"varint,7,opt,name=opens_count,json=opensCount,proto3" json:"opens_count,omitempty"`
	ConversionRate     *RateField             `protobuf:"bytes,8,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	Settings           []*structpb.Struct     `protobuf:"bytes,9,rep,name=settings,proto3" json:"settings,omitempty"`
	LastRegistrationAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_registration_at,json=lastRegistrationAt,proto3" json:"last_registration_at,omitempty"`
	Active             bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	IsBroken           bool                   `protobuf:"varint,12,opt,name=is_broken,json=isBroken,proto3" json:"is_broken,omitempty"`
	HasContent         bool                   `protobuf:"varint,13,opt,name=has_content,json=hasContent,proto3" json:"has_content,omitempty"`
	UsedInAutomations  bool                   `protobuf:"varint,14,opt,name=used_in_automations,json=usedInAutomations,proto3" json:"used_in_automations,omitempty"`
	DoubleOptin        bool                   `protobuf:"varint,15,opt,name=double_optin,json=doubleOptin,proto3" json:"double_optin,omitempty"`
	ScreenshotUrl      string                 `protobuf:"bytes,16,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"`
	Custom             *structpb.Struct       `protobuf:"bytes,17,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormResponse) Reset() {
	*x = FormResponse{}
	mi := &file_audience_v1_forms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormResponse) ProtoMessage() {}

func (x *FormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormResponse.ProtoReflect.Descriptor instead.
func (*FormResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{4}
}

func (x *FormResponse) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *FormResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FormResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *FormResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FormResponse) GetConversionsCount() int32 {
	if x != nil {
		return x.ConversionsCount
	}
	return 0
}

func (x *FormResponse) GetOpensCount() int32 {
	if x != nil {
		return x.OpensCount
	}
	return 0
}

func (x *FormResponse) GetConversionRate() *RateField {
	if x != nil {
		return x.ConversionRate
	}
	return nil
}

func (x *FormResponse) GetSettings() []*structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *FormResponse) GetLastRegistrationAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRegistrationAt
	}
	return nil
}

func (x *FormResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *FormResponse) GetIsBroken() bool {
	if x != nil {
		return x.IsBroken
	}
	return false
}

func (x *FormResponse) GetHasContent() bool {
	if x != nil {
		return x.HasContent
	}
	return false
}

func (x *FormResponse) GetUsedInAutomations() bool {
	if x != nil {
		return x.UsedInAutomations
	}
	return false
}

func (x *FormResponse) GetDoubleOptin() bool {
	if x != nil {
		return x.DoubleOptin
	}
	return false
}

func (x *FormResponse) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

func (x *FormResponse) GetCustom() *structpb.Struct {
	if x != nil {
		return x.Custom
	}
	return nil
}

// پاسخ لیست
type ListFormsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FormResponse        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsResponse) Reset() {
	*x = ListFormsResponse{}
	mi := &file_audience_v1_forms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsResponse) ProtoMessage() {}

func (x *ListFormsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsResponse.ProtoReflect.Descriptor instead.
func (*ListFormsResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{5}
}

func (x *ListFormsResponse) GetItems() []*FormResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFormsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFormsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFormsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// پاسخ حذف
type DeleteFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormResponse) Reset() {
	*x = DeleteFormResponse{}
	mi := &file_audience_v1_forms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormResponse) ProtoMessage() {}

func (x *DeleteFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormResponse.ProtoReflect.Descriptor instead.
func (*DeleteFormResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFormResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFormResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// نرخ به دو صورت عدد و متن
type RateField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         float64                `protobuf:"fixed64,1,opt,name=float,proto3" json:"float,omitempty"`
	StringValue   string                 `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateField) Reset() {
	*x = RateField{}
	mi := &file_audience_v1_forms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateField) ProtoMessage() {}

func (x *RateField) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_forms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateField.ProtoReflect.Descriptor instead.
func (*RateField) Descriptor() ([]byte, []int) {
	return file_audience_v1_forms_proto_rawDescGZIP(), []int{7}
}

func (x *RateField) GetFloat() float64 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *RateField) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

var File_audience_v1_forms_proto protoreflect.FileDescriptor

const file_audience_v1_forms_proto_rawDesc = "" +
	"\n" +
	"\x17audience/v1/forms.proto\x12\vaudience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"l\n" +
	"\x11CreateFormRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\x06custom\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06custom\"q\n" +
	"\x11UpdateFormRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06custom\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06custom\"\xbf\x01\n" +
	"\x10ListFormsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\tR\tsortOrder\",\n" +
	"\x11DeleteFormRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\"\xb1\x05\n" +
	"\fFormResponse\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11conversions_count\x18\x06 \x01(\x05R\x10conversionsCount\x12\x1f\n" +
	"\vopens_count\x18\a \x01(\x05R\n" +
	"opensCount\x12?\n" +
	"\x0fconversion_rate\x18\b \x01(\v2\x16.audience.v1.RateFieldR\x0econversionRate\x123\n" +
	"\bsettings\x18\t \x03(\v2\x17.google.protobuf.StructR\bsettings\x12L\n" +
	"\x14last_registration_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12lastRegistrationAt\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\x12\x1b\n" +
	"\tis_broken\x18\f \x01(\bR\bisBroken\x12\x1f\n" +
	"\vhas_content\x18\r \x01(\bR\n" +
	"hasContent\x12.\n" +
	"\x13used_in_automations\x18\x0e \x01(\bR\x11usedInAutomations\x12!\n" +
	"\fdouble_optin\x18\x0f \x01(\bR\vdoubleOptin\x12%\n" +
	"\x0escreenshot_url\x18\x10 \x01(\tR\rscreenshotUrl\x12/\n" +
	"\x06custom\x18\x11 \x01(\v2\x17.google.protobuf.StructR\x06custom\"\x8b\x01\n" +
	"\x11ListFormsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.audience.v1.FormResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"H\n" +
	"\x12DeleteFormResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\tRateField\x12\x14\n" +
	"\x05float\x18\x01 \x01(\x01R\x05float\x12!\n" +
	"\fstring_value\x18\x02 \x01(\tR\vstringValue2\xba\x02\n" +
	"\vFormService\x12G\n" +
	"\n" +
	"CreateForm\x12\x1e.audience.v1.CreateFormRequest\x1a\x19.audience.v1.FormResponse\x12G\n" +
	"\n" +
	"UpdateForm\x12\x1e.audience.v1.UpdateFormRequest\x1a\x19.audience.v1.FormResponse\x12J\n" +
	"\tListForms\x12\x1d.audience.v1.ListFormsRequest\x1a\x1e.audience.v1.ListFormsResponse\x12M\n" +
	"\n" +
	"DeleteForm\x12\x1e.audience.v1.DeleteFormRequest\x1a\x1f.audience.v1.DeleteFormResponseBFZDgithub.com/ehsanshah/empire-protos/src/pkg/pb/audience/v1;audiencev1b\x06proto3"

var (
	file_audience_v1_forms_proto_rawDescOnce sync.Once
	file_audience_v1_forms_proto_rawDescData []byte
)

func file_audience_v1_forms_proto_rawDescGZIP() []byte {
	file_audience_v1_forms_proto_rawDescOnce.Do(func() {
		file_audience_v1_forms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audience_v1_forms_proto_rawDesc), len(file_audience_v1_forms_proto_rawDesc)))
	})
	return file_audience_v1_forms_proto_rawDescData
}

var file_audience_v1_forms_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_audience_v1_forms_proto_goTypes = []any{
	(*CreateFormRequest)(nil),     // 0: audience.v1.CreateFormRequest
	(*UpdateFormRequest)(nil),     // 1: audience.v1.UpdateFormRequest
	(*ListFormsRequest)(nil),      // 2: audience.v1.ListFormsRequest
	(*DeleteFormRequest)(nil),     // 3: audience.v1.DeleteFormRequest
	(*FormResponse)(nil),          // 4: audience.v1.FormResponse
	(*ListFormsResponse)(nil),     // 5: audience.v1.ListFormsResponse
	(*DeleteFormResponse)(nil),    // 6: audience.v1.DeleteFormResponse
	(*RateField)(nil),             // 7: audience.v1.RateField
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_audience_v1_forms_proto_depIdxs = []int32{
	8,  // 0: audience.v1.CreateFormRequest.custom:type_name -> google.protobuf.Struct
	8,  // 1: audience.v1.UpdateFormRequest.custom:type_name -> google.protobuf.Struct
	9,  // 2: audience.v1.FormResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: audience.v1.FormResponse.conversion_rate:type_name -> audience.v1.RateField
	8,  // 4: audience.v1.FormResponse.settings:type_name -> google.protobuf.Struct
	9,  // 5: audience.v1.FormResponse.last_registration_at:type_name -> google.protobuf.Timestamp
	8,  // 6: audience.v1.FormResponse.custom:type_name -> google.protobuf.Struct
	4,  // 7: audience.v1.ListFormsResponse.items:type_name -> audience.v1.FormResponse
	0,  // 8: audience.v1.FormService.CreateForm:input_type -> audience.v1.CreateFormRequest
	1,  // 9: audience.v1.FormService.UpdateForm:input_type -> audience.v1.UpdateFormRequest
	2,  // 10: audience.v1.FormService.ListForms:input_type -> audience.v1.ListFormsRequest
	3,  // 11: audience.v1.FormService.DeleteForm:input_type -> audience.v1.DeleteFormRequest
	4,  // 12: audience.v1.FormService.CreateForm:output_type -> audience.v1.FormResponse
	4,  // 13: audience.v1.FormService.UpdateForm:output_type -> audience.v1.FormResponse
	5,  // 14: audience.v1.FormService.ListForms:output_type -> audience.v1.ListFormsResponse
	6,  // 15: audience.v1.FormService.DeleteForm:output_type -> audience.v1.DeleteFormResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_audience_v1_forms_proto_init() }
func file_audience_v1_forms_proto_init() {
	if File_audience_v1_forms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audience_v1_forms_proto_rawDesc), len(file_audience_v1_forms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audience_v1_forms_proto_goTypes,
		DependencyIndexes: file_audience_v1_forms_proto_depIdxs,
		MessageInfos:      file_audience_v1_forms_proto_msgTypes,
	}.Build()
	File_audience_v1_forms_proto = out.File
	file_audience_v1_forms_proto_goTypes = nil
	file_audience_v1_forms_proto_depIdxs = nil
}
