// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: audience/v1/segments.proto

package audiencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ساخت سگمنت جدید
type CreateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // نام سگمنت (مثلاً "خریداران تهران")
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`                         // قانون یا فیلتر سگمنت (مثلاً "city = 'Tehran' AND active = true")
	ListName      string                 `protobuf:"bytes,3,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"` // نام لیست مرجع
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentRequest) Reset() {
	*x = CreateSegmentRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentRequest) ProtoMessage() {}

func (x *CreateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSegmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSegmentRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *CreateSegmentRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

// ویرایش سگمنت
type UpdateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // شناسه سگمنت
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // نام جدید
	Rule          string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`                            // قانون جدید
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSegmentRequest) Reset() {
	*x = UpdateSegmentRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentRequest) ProtoMessage() {}

func (x *UpdateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *UpdateSegmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSegmentRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

// دریافت لیست سگمنت‌ها
type ListSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListName      string                 `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"` // نام لیست هدف (اختیاری)
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                        // شماره صفحه
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // تعداد آیتم هر صفحه
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`                     // فیلتر جستجو (اختیاری)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{2}
}

func (x *ListSegmentsRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *ListSegmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSegmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSegmentsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// دریافت جزئیات یک سگمنت
type GetSegmentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // شناسه سگمنت هدف
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentDetailRequest) Reset() {
	*x = GetSegmentDetailRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentDetailRequest) ProtoMessage() {}

func (x *GetSegmentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentDetailRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{3}
}

func (x *GetSegmentDetailRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

// کپی‌کردن سگمنت
type CopySegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // شناسه سگمنت برای کپی
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`       // نام جدید برای سگمنت کپی‌شده
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopySegmentRequest) Reset() {
	*x = CopySegmentRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopySegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopySegmentRequest) ProtoMessage() {}

func (x *CopySegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopySegmentRequest.ProtoReflect.Descriptor instead.
func (*CopySegmentRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{4}
}

func (x *CopySegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *CopySegmentRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// ساخت سگمنت از روی فایل
type CreateSegmentFromFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // فایل آپلودشده (CSV یا json)
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`          // نوع فایل (مثلاً "csv")
	ListName      string                 `protobuf:"bytes,3,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`          // نام لیست هدف
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                  // نام سگمنت جدید
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentFromFileRequest) Reset() {
	*x = CreateSegmentFromFileRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentFromFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentFromFileRequest) ProtoMessage() {}

func (x *CreateSegmentFromFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentFromFileRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentFromFileRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSegmentFromFileRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *CreateSegmentFromFileRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *CreateSegmentFromFileRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *CreateSegmentFromFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// تست قانون سگمنت روی داده نمونه
type TestSegmentRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`                         // قانون سگمنت (مثلاً "age > 18")
	ListName      string                 `protobuf:"bytes,2,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"` // نام لیست هدف (اختیاری)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSegmentRuleRequest) Reset() {
	*x = TestSegmentRuleRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSegmentRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSegmentRuleRequest) ProtoMessage() {}

func (x *TestSegmentRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSegmentRuleRequest.ProtoReflect.Descriptor instead.
func (*TestSegmentRuleRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{6}
}

func (x *TestSegmentRuleRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *TestSegmentRuleRequest) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

// تست یک سگمنت ذخیره‌شده با ID
type TestSegmentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // شناسه سگمنت هدف
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSegmentByIDRequest) Reset() {
	*x = TestSegmentByIDRequest{}
	mi := &file_audience_v1_segments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSegmentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSegmentByIDRequest) ProtoMessage() {}

func (x *TestSegmentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSegmentByIDRequest.ProtoReflect.Descriptor instead.
func (*TestSegmentByIDRequest) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{7}
}

func (x *TestSegmentByIDRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

// اطلاعات سگمنت (پاسخ ساخت/ویرایش/کپی/جزئیات)
type SegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`              // شناسه سگمنت
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                         // نام سگمنت
	Rule          string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`                                         // قانون سگمنت
	ListName      string                 `protobuf:"bytes,4,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`                 // نام لیست مرجع
	DateAdded     string                 `protobuf:"bytes,5,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`              // تاریخ ساخت
	ContactsCount int32                  `protobuf:"varint,6,opt,name=contacts_count,json=contactsCount,proto3" json:"contacts_count,omitempty"` // تعداد مخاطبین مطابق این سگمنت
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentResponse) Reset() {
	*x = SegmentResponse{}
	mi := &file_audience_v1_segments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentResponse) ProtoMessage() {}

func (x *SegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentResponse.ProtoReflect.Descriptor instead.
func (*SegmentResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{8}
}

func (x *SegmentResponse) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentResponse) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *SegmentResponse) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *SegmentResponse) GetDateAdded() string {
	if x != nil {
		return x.DateAdded
	}
	return ""
}

func (x *SegmentResponse) GetContactsCount() int32 {
	if x != nil {
		return x.ContactsCount
	}
	return 0
}

// لیست سگمنت‌ها (صفحه‌بندی)
type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SegmentResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`  // لیست سگمنت‌ها
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // تعداد کل سگمنت‌ها
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // شماره صفحه فعلی
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // اندازه صفحه
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_audience_v1_segments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{9}
}

func (x *ListSegmentsResponse) GetItems() []*SegmentResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSegmentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSegmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSegmentsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// پاسخ تست قانون سگمنت (نمونه خروجی)
type TestSegmentRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // نتیجه تست (آیا قانون درست کار می‌کند)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                // پیام توضیحی یا خطا
	MatchedCount  int32                  `protobuf:"varint,3,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"` // تعداد مخاطب مطابقت داده‌شده
	SampleEmails  []string               `protobuf:"bytes,4,rep,name=sample_emails,json=sampleEmails,proto3" json:"sample_emails,omitempty"`  // نمونه ایمیل‌های انتخاب‌شده
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSegmentRuleResponse) Reset() {
	*x = TestSegmentRuleResponse{}
	mi := &file_audience_v1_segments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSegmentRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSegmentRuleResponse) ProtoMessage() {}

func (x *TestSegmentRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audience_v1_segments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSegmentRuleResponse.ProtoReflect.Descriptor instead.
func (*TestSegmentRuleResponse) Descriptor() ([]byte, []int) {
	return file_audience_v1_segments_proto_rawDescGZIP(), []int{10}
}

func (x *TestSegmentRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestSegmentRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestSegmentRuleResponse) GetMatchedCount() int32 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *TestSegmentRuleResponse) GetSampleEmails() []string {
	if x != nil {
		return x.SampleEmails
	}
	return nil
}

var File_audience_v1_segments_proto protoreflect.FileDescriptor

const file_audience_v1_segments_proto_rawDesc = "" +
	"\n" +
	"\x1aaudience/v1/segments.proto\x12\vaudience.v1\"[\n" +
	"\x14CreateSegmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x1b\n" +
	"\tlist_name\x18\x03 \x01(\tR\blistName\"]\n" +
	"\x14UpdateSegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\"t\n" +
	"\x13ListSegmentsRequest\x12\x1b\n" +
	"\tlist_name\x18\x01 \x01(\tR\blistName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"8\n" +
	"\x17GetSegmentDetailRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\"N\n" +
	"\x12CopySegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x8f\x01\n" +
	"\x1cCreateSegmentFromFileRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12\x1b\n" +
	"\tlist_name\x18\x03 \x01(\tR\blistName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"I\n" +
	"\x16TestSegmentRuleRequest\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x1b\n" +
	"\tlist_name\x18\x02 \x01(\tR\blistName\"7\n" +
	"\x16TestSegmentByIDRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\"\xbb\x01\n" +
	"\x0fSegmentResponse\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x1b\n" +
	"\tlist_name\x18\x04 \x01(\tR\blistName\x12\x1d\n" +
	"\n" +
	"date_added\x18\x05 \x01(\tR\tdateAdded\x12%\n" +
	"\x0econtacts_count\x18\x06 \x01(\x05R\rcontactsCount\"\x8a\x01\n" +
	"\x14ListSegmentsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.audience.v1.SegmentResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x97\x01\n" +
	"\x17TestSegmentRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rmatched_count\x18\x03 \x01(\x05R\fmatchedCount\x12#\n" +
	"\rsample_emails\x18\x04 \x03(\tR\fsampleEmails2\xcd\x05\n" +
	"\x0eSegmentService\x12P\n" +
	"\rCreateSegment\x12!.audience.v1.CreateSegmentRequest\x1a\x1c.audience.v1.SegmentResponse\x12P\n" +
	"\rUpdateSegment\x12!.audience.v1.UpdateSegmentRequest\x1a\x1c.audience.v1.SegmentResponse\x12S\n" +
	"\fListSegments\x12 .audience.v1.ListSegmentsRequest\x1a!.audience.v1.ListSegmentsResponse\x12V\n" +
	"\x10GetSegmentDetail\x12$.audience.v1.GetSegmentDetailRequest\x1a\x1c.audience.v1.SegmentResponse\x12L\n" +
	"\vCopySegment\x12\x1f.audience.v1.CopySegmentRequest\x1a\x1c.audience.v1.SegmentResponse\x12`\n" +
	"\x15CreateSegmentFromFile\x12).audience.v1.CreateSegmentFromFileRequest\x1a\x1c.audience.v1.SegmentResponse\x12\\\n" +
	"\x0fTestSegmentRule\x12#.audience.v1.TestSegmentRuleRequest\x1a$.audience.v1.TestSegmentRuleResponse\x12\\\n" +
	"\x0fTestSegmentByID\x12#.audience.v1.TestSegmentByIDRequest\x1a$.audience.v1.TestSegmentRuleResponseBFZDgithub.com/ehsanshah/empire-protos/src/pkg/pb/audience/v1;audiencev1b\x06proto3"

var (
	file_audience_v1_segments_proto_rawDescOnce sync.Once
	file_audience_v1_segments_proto_rawDescData []byte
)

func file_audience_v1_segments_proto_rawDescGZIP() []byte {
	file_audience_v1_segments_proto_rawDescOnce.Do(func() {
		file_audience_v1_segments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audience_v1_segments_proto_rawDesc), len(file_audience_v1_segments_proto_rawDesc)))
	})
	return file_audience_v1_segments_proto_rawDescData
}

var file_audience_v1_segments_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_audience_v1_segments_proto_goTypes = []any{
	(*CreateSegmentRequest)(nil),         // 0: audience.v1.CreateSegmentRequest
	(*UpdateSegmentRequest)(nil),         // 1: audience.v1.UpdateSegmentRequest
	(*ListSegmentsRequest)(nil),          // 2: audience.v1.ListSegmentsRequest
	(*GetSegmentDetailRequest)(nil),      // 3: audience.v1.GetSegmentDetailRequest
	(*CopySegmentRequest)(nil),           // 4: audience.v1.CopySegmentRequest
	(*CreateSegmentFromFileRequest)(nil), // 5: audience.v1.CreateSegmentFromFileRequest
	(*TestSegmentRuleRequest)(nil),       // 6: audience.v1.TestSegmentRuleRequest
	(*TestSegmentByIDRequest)(nil),       // 7: audience.v1.TestSegmentByIDRequest
	(*SegmentResponse)(nil),              // 8: audience.v1.SegmentResponse
	(*ListSegmentsResponse)(nil),         // 9: audience.v1.ListSegmentsResponse
	(*TestSegmentRuleResponse)(nil),      // 10: audience.v1.TestSegmentRuleResponse
}
var file_audience_v1_segments_proto_depIdxs = []int32{
	8,  // 0: audience.v1.ListSegmentsResponse.items:type_name -> audience.v1.SegmentResponse
	0,  // 1: audience.v1.SegmentService.CreateSegment:input_type -> audience.v1.CreateSegmentRequest
	1,  // 2: audience.v1.SegmentService.UpdateSegment:input_type -> audience.v1.UpdateSegmentRequest
	2,  // 3: audience.v1.SegmentService.ListSegments:input_type -> audience.v1.ListSegmentsRequest
	3,  // 4: audience.v1.SegmentService.GetSegmentDetail:input_type -> audience.v1.GetSegmentDetailRequest
	4,  // 5: audience.v1.SegmentService.CopySegment:input_type -> audience.v1.CopySegmentRequest
	5,  // 6: audience.v1.SegmentService.CreateSegmentFromFile:input_type -> audience.v1.CreateSegmentFromFileRequest
	6,  // 7: audience.v1.SegmentService.TestSegmentRule:input_type -> audience.v1.TestSegmentRuleRequest
	7,  // 8: audience.v1.SegmentService.TestSegmentByID:input_type -> audience.v1.TestSegmentByIDRequest
	8,  // 9: audience.v1.SegmentService.CreateSegment:output_type -> audience.v1.SegmentResponse
	8,  // 10: audience.v1.SegmentService.UpdateSegment:output_type -> audience.v1.SegmentResponse
	9,  // 11: audience.v1.SegmentService.ListSegments:output_type -> audience.v1.ListSegmentsResponse
	8,  // 12: audience.v1.SegmentService.GetSegmentDetail:output_type -> audience.v1.SegmentResponse
	8,  // 13: audience.v1.SegmentService.CopySegment:output_type -> audience.v1.SegmentResponse
	8,  // 14: audience.v1.SegmentService.CreateSegmentFromFile:output_type -> audience.v1.SegmentResponse
	10, // 15: audience.v1.SegmentService.TestSegmentRule:output_type -> audience.v1.TestSegmentRuleResponse
	10, // 16: audience.v1.SegmentService.TestSegmentByID:output_type -> audience.v1.TestSegmentRuleResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_audience_v1_segments_proto_init() }
func file_audience_v1_segments_proto_init() {
	if File_audience_v1_segments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audience_v1_segments_proto_rawDesc), len(file_audience_v1_segments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audience_v1_segments_proto_goTypes,
		DependencyIndexes: file_audience_v1_segments_proto_depIdxs,
		MessageInfos:      file_audience_v1_segments_proto_msgTypes,
	}.Build()
	File_audience_v1_segments_proto = out.File
	file_audience_v1_segments_proto_goTypes = nil
	file_audience_v1_segments_proto_depIdxs = nil
}
